// Crew Roll's interface text, in English and French.

export const T = {
  en: {
    title: "Crew Roll",
    sub: "Roll random characters and build the strongest crew. Every placement counts.",
    solo: "Solo",
    online: "Online",
    pick: "Anime",
    modeLabel: "Mode",
    arcLabel: "Arc",
    allArcs: "All arcs",
    roll: "Roll a character",
    draw: "Draw",
    waitingRoll: "Who joins the crew?",
    captainTag: "Leader",
    skip: "No slot left for this one: skip",
    tiers: { legend: "Legendary", epic: "Epic", common: "Common" },
    teamWins: (n) => `${n} wins!`,
    teamDraw: "Draw between the teams!",
    index: "Index",
    boosters: "Boosters",
    bTitle: "Boosters",
    bSub: "5 cards per pack, the last one Epic or better. Every new card joins your collection.",
    bStock: (n) => (n ? `${n} booster${n > 1 ? "s" : ""} to open` : "No booster to open"),
    bHow: "Earn them: 3 as a welcome gift, 1 a day, 1 per win (any game) and per crew built. 10 at most in stock.",
    bNext: (h) => `Next daily booster in ${h}`,
    bOwned: (a, b) => `${a} / ${b}`,
    bOpen: "Open",
    bNone: "No booster left",
    bTap: "Click to unzip the pack",
    bSkip: "Skip",
    bFlip: "Tap the cards to reveal them",
    bFlipAll: "Reveal all",
    bNew: "New",
    bDupe: "Duplicate",
    bSummary: (n) => (n ? `${n} new card${n > 1 ? "s" : ""}!` : "No new card this time"),
    bAgain: "Open another",
    bQty: "Open",
    bAll: "All",
    bTapMany: (n) => `${n} boosters: click to unzip them all`,
    bManyDetail: (n, e, l, s) => `${n} cards · ${e} Epic · ${l} Legendary${s ? ` · ${s} Secret` : ""}`,
    bDone: "Done",
    bShow: "★ Showcase",
    bShowOn: "★ In showcase",
    bRates: "Rates per card: Common 75 % · Epic 21 % · Legendary 4 % · Secret (transformation) 1 %",
    secret: "Secret",
    indexTitle: (a) => `${a} index`,
    indexSub: (n, arc) => `${n} cards${arc ? ` · spoiler-free up to ${arc}` : ""}. What each card scores in every role.`,
    indexSearch: "Search a character…",
    indexSort: "Sort",
    sortPower: "Power",
    sortName: "Name",
    allTiers: "All",
    dropTitle: "Drop rates",
    dropNote: (n) => `Every draw is random among the characters that still fit your crew: each of the ${n} cards has the same chance (1 in ${n} on the first draw).`,
    bestRole: "Best role",
    noFit: "Can't go in this role",
    noCard: "No card matches.",
    newCard: "✨ New card!", collection: (a, b) => `Collection · ${a} / ${b}`, ownAll: "All", ownYes: "Owned", ownNo: "To find", notDrawn: "Not owned yet (boosters)",
    ixTop: "Best crews",
    ixBoard: "Full leaderboard",
    ixNone: "No crew yet for this anime: build one in Solo!",
    ixTap: "Tap to see the transformation",
    rolling: "Rolling…",
    chooseSlot: "Choose a slot for this character",
    noSlot: "No free slot fits this character",
    reroll: (n) => `Reroll (${n} left)`,
    score: "Score",
    filled: (a, b) => `${a}/${b} slots`,
    power: "Power",
    spoiler: (arc) => `Spoiler-free up to: ${arc}`,
    spoilerAll: "All arcs (set your arc in the guessing game to limit spoilers)",
    resultTitle: "Your crew is complete!",
    best: "Best pick",
    worst: "Weakest pick",
    share: "Copy result",
    copied: "Result copied!",
    again: "New crew",
    empty: "Empty",
    lobbyTitle: "Lobby",
    lobbyHelp: "Create a room for 2 to 8 players, or join an open one. Players take turns: roll, place, and watch the others' picks live (3 rerolls each); the best crew wins.",
    yourName: "Your name",
    saveName: "Save",
    nameSaved: "Name saved",
    players: "Players",
    createRoom: "Create a room",
    openRooms: "Open rooms",
    noRooms: "No open room yet: create one and share the page!",
    inLobby: (n) => `In the lobby (${n})`,
    join: "Join",
    roomOf: (n) => `${n}'s room`,
    host: "host",
    freeSeat: "Free seat",
    start: "Start the match",
    leave: "Leave",
    waitHost: "Waiting for the host to start…",
    needTwo: "At least 2 players are needed to start.",
    roomClosed: "The host closed the room.",
    rejoining: "Getting you back into your match…",
    rejoined: "Back in the match!",
    lateJoined: (n) => `${n} joins the match and will catch up!`,
    rejoinFailed: "Your match couldn't be found anymore.",
    invite: "Invite",
    inviteSent: (n) => `Invitation sent to ${n}`,
    invitedBy: (n, a) => `${n} invites you to play${a ? ` (${a})` : ""}`,
    ignore: "Ignore",
    withCode: "Join with a code",
    codePlaceholder: "Room code",
    joinCode: "Join",
    codeLabel: "Room code",
    copyCode: "Copy",
    codeCopied: "Code copied!",
    codeNotFound: "No open room with this code.",
    searching: "Looking for the room…",
    aloneHere: "Nobody else is on this page yet. Send the link to your friends: they'll show up here with an Invite button.",
    copyLink: "Copy the link",
    linkCopied: "Link copied!",
    copyInvite: "Copy the invite link",
    inviteCopied: "Link copied! Send it to your friends.",
    joiningLink: "Joining the room from your link…",
    linkGone: "This room is full, already playing or closed.",
    pickToJoin: "Pick a name to join the room.",
    hostPicks: "You're the host: change the anime below, everyone follows.",
    hostChooses: "The host picks the anime.",
    connecting: "Connecting to the lobby…",
    offline: "Online play is unavailable right now.",
    you: "you",
    taken: (n) => `${n} already took this character: free roll!`,
    arcUsed: (arc) => `Arc: ${arc} (the lowest in the room, so nobody is spoiled)`,
    lockedNote: (roles) => `Not reached yet at this arc: ${roles}`,
    waitOthers: "Waiting for the other players…",
    yourTurn: "Your turn!",
    turnOf: (n) => `${n}'s turn…`,
    autoIn: (s) => `Auto-play in ${s} s`,
    skipped: "No free slot fits: skipped",
    finalRanking: "Final ranking",
    youPlace: (n) => (n === 1 ? "You win!" : `You finish #${n}`),
    left: "left",
    tie: "Tie for first!",
    backRoom: "Back to the room",
    vs: "VS",
    pickName: "Pick a name first",
    cards: "Cards",
    back: "Back",
    cTitle: "My cards",
    cSub: "Your booster cards: your inventory with its duplicates, trades with your friends and card duels from 2 to 8 players.",
    cInventory: "Inventory",
    cTrades: "Trades",
    cDuels: "Duels",
    cUnique: "different cards",
    cCopies: "cards in all",
    cDupes: "duplicates",
    cGoBoosters: "Open boosters",
    cNoCards: "No card yet: open boosters to start your collection.",
    cOnlyDupes: "Duplicates only",
    cTradeThis: "Trade this card",
    cRemove: "Take out of the deck",
    cTradeErr: { mine: "You don't have this card anymore.", theirs: "Your friend doesn't have this card anymore.", gone: "This offer no longer exists.", friend: "You can only trade with your friends.", card: "Invalid card.", auth: "Create a profile to trade." },
    cMakeProfile: "Create my profile",
    cNeedProfile: "Trades are between friends: create a profile and add your friends first.",
    cNewTrade: "Propose a trade",
    cGot: (n) => `Offers received (${n})`,
    cNoneGot: "No offer for now.",
    cAccept: "Accept",
    cDecline: "Decline",
    cTradeOk: "Trade done! Check your inventory.",
    cSent: (n) => `Offers sent (${n})`,
    cNoneSent: "You haven't sent any offer.",
    cCancel: "Cancel",
    cOfferFrom: (n) => `${n} offers you a trade`,
    cOfferTo: (n) => `Your offer to ${n}`,
    cYouGet: "You get",
    cYouGive: "You give",
    cChange: "Change",
    cStepFriend: "Friend",
    cStepGive: "Your card",
    cStepWant: "Their card",
    cGift: "Nothing (a gift)",
    cPickFriend: "Who do you want to trade with?",
    cNoFriends: "No friend yet: add some in your profile (Friends tab).",
    cPickGive: "Which card do you give?",
    cPickGiveHelp: "Your duplicates come first: giving one keeps the card in your collection.",
    cPickWant: (n) => `Which card of ${n} do you want?`,
    cNothing: "Nothing, it's a gift",
    cTheyHaveNone: "This friend has no card yet.",
    cSend: "Send the offer",
    cSentOk: (n) => `Offer sent to ${n}!`,
    cInvitedBy: (n, m) => `${n} challenges you to a ${m}`,
    cPackBattle: "Pack battle",
    cDeckBattle: "Deck battle",
    cPackHelp: "Everyone opens a pack of the same anime in turn, three times: the strongest pack wins the round (power + rarity). Pure luck!",
    cDeckHelp: "Bring 5 cards of your collection and play one per round: power ×10, +8 if it transforms, + a roll of the dice. Best of 5.",
    cDuelTitle: "Card duels",
    cDuelHelp: "Pack or deck battle, from 2 to 8 players, alone or in teams. Winning gets you a booster.",
    cNeedName: "Pick a name in the online bar to play online.",
    cCreate: "Create a duel",
    cDeckFirst: "Build your deck of 5 cards first.",
    cNoDuels: "No open duel: create one!",
    cAlone: "Nobody else on the duels page right now: invite a friend from your profile once your duel is created.",
    cMyDeck: (a, b) => `My deck · ${a} / ${b}`,
    cDeckNeed: (n) => `You need at least ${n} cards: open boosters!`,
    cDeckAuto: "My 5 strongest",
    cRound: (a, b) => `Round ${a} / ${b}`,
    cOpening: "Opening…",
    cOpenMine: "Open",
    cYourPack: "Your turn: tear your pack open!",
    cTheirPack: (n) => `${n} is opening their pack…`,
    cRoundWon: "Round won!",
    cRoundLost: "Round lost",
    cRoundTie: "Tie",
    cWaitDeck: "Waiting for their deck…",
    cPlayCard: "Play a card",
    cPickPlay: "Pick the card you play this round",
    cWaitPlay: (n) => `Waiting for ${n}…`,
    cWin: "Victory!",
    cWinForfeit: "Victory: your opponent left",
    cLose: "Defeat",
    cDraw: "Draw",
    cWinBooster: "+1 booster",
    cTeamsNote: "From 3 players, the host can split the room into two teams: each round, the team with the larger total wins.",
    cRoundShared: "Round shared!",
    cRoundBy: (n) => `Round for ${n}`,
  },
  fr: {
    title: "Roll ton équipage",
    sub: "Tire des personnages au hasard et construis l'équipage le plus fort. Chaque placement compte.",
    solo: "Solo",
    online: "En ligne",
    pick: "Anime",
    modeLabel: "Mode",
    arcLabel: "Arc",
    allArcs: "Tous les arcs",
    roll: "Tirer un personnage",
    draw: "Tirage",
    waitingRoll: "Qui rejoint l'équipage ?",
    captainTag: "Chef",
    skip: "Plus de place pour lui : passer",
    tiers: { legend: "Légendaire", epic: "Épique", common: "Commun" },
    teamWins: (n) => `${n} gagne !`,
    teamDraw: "Égalité entre les équipes !",
    index: "Index",
    boosters: "Boosters",
    bTitle: "Boosters",
    bSub: "5 cartes par booster, la dernière au moins Épique. Chaque nouvelle carte rejoint ta collection.",
    bStock: (n) => (n ? `${n} booster${n > 1 ? "s" : ""} à ouvrir` : "Aucun booster à ouvrir"),
    bHow: "Pour en gagner : 3 en cadeau de bienvenue, 1 par jour, 1 par victoire (tous les jeux) et par équipage construit. 10 maximum en stock.",
    bNext: (h) => `Prochain booster du jour dans ${h}`,
    bOwned: (a, b) => `${a} / ${b}`,
    bOpen: "Ouvrir",
    bNone: "Plus de booster",
    bTap: "Clique pour ouvrir le zip du booster",
    bSkip: "Passer",
    bFlip: "Touche les cartes pour les révéler",
    bFlipAll: "Tout révéler",
    bNew: "Nouvelle",
    bDupe: "Doublon",
    bSummary: (n) => (n ? `${n} nouvelle${n > 1 ? "s" : ""} carte${n > 1 ? "s" : ""} !` : "Pas de nouvelle carte cette fois"),
    bAgain: "En ouvrir un autre",
    bQty: "Ouvrir",
    bAll: "Tout",
    bTapMany: (n) => `${n} boosters : clique pour tous les ouvrir`,
    bManyDetail: (n, e, l, s) => `${n} cartes · ${e} Épique${e > 1 ? "s" : ""} · ${l} Légendaire${l > 1 ? "s" : ""}${s ? ` · ${s} Secrète${s > 1 ? "s" : ""}` : ""}`,
    bDone: "Terminé",
    bShow: "★ Vitrine",
    bShowOn: "★ En vitrine",
    bRates: "Taux par carte : Commune 75 % · Épique 21 % · Légendaire 4 % · Secrète (transformation) 1 %",
    secret: "Secrète",
    indexTitle: (a) => `Index ${a}`,
    indexSub: (n, arc) => `${n} cartes${arc ? ` · sans spoiler jusqu'à ${arc}` : ""}. Ce que chaque carte rapporte dans chaque rôle.`,
    indexSearch: "Chercher un personnage…",
    indexSort: "Trier",
    sortPower: "Puissance",
    sortName: "Nom",
    allTiers: "Toutes",
    dropTitle: "Taux de drop",
    dropNote: (n) => `Chaque tirage se fait au hasard parmi les persos qui ont encore une place dans ton équipage : les ${n} cartes ont toutes la même chance (1 sur ${n} au premier tirage).`,
    bestRole: "Meilleur rôle",
    noFit: "Ne peut pas aller à ce rôle",
    noCard: "Aucune carte ne correspond.",
    newCard: "✨ Nouvelle carte !", collection: (a, b) => `Collection · ${a} / ${b}`, ownAll: "Toutes", ownYes: "Obtenues", ownNo: "À trouver", notDrawn: "Pas encore obtenue (boosters)",
    ixTop: "Meilleurs équipages",
    ixBoard: "Classement complet",
    ixNone: "Pas encore d'équipage pour cet animé : fais-en un en Solo !",
    ixTap: "Touche pour voir la transformation",
    rolling: "Tirage…",
    chooseSlot: "Choisis une place pour ce personnage",
    noSlot: "Aucune place libre ne convient à ce personnage",
    reroll: (n) => `Relancer (${n} restant${n > 1 ? "s" : ""})`,
    score: "Score",
    filled: (a, b) => `${a}/${b} places`,
    power: "Puissance",
    spoiler: (arc) => `Sans spoiler jusqu'à : ${arc}`,
    spoilerAll: "Tous les arcs (choisis ton arc dans le jeu de devinette pour limiter les spoilers)",
    resultTitle: "Ton équipage est complet !",
    best: "Meilleur choix",
    worst: "Choix le plus faible",
    share: "Copier le résultat",
    copied: "Résultat copié !",
    again: "Nouvel équipage",
    empty: "Libre",
    lobbyTitle: "Lobby",
    lobbyHelp: "Crée une salle de 2 à 8 joueurs, ou rejoins-en une. On joue chacun son tour : tire, place, et regarde les persos des autres en direct (3 relances chacun) : le meilleur équipage gagne.",
    yourName: "Ton pseudo",
    saveName: "OK",
    nameSaved: "Pseudo enregistré",
    players: "Joueurs",
    createRoom: "Créer une salle",
    openRooms: "Salles ouvertes",
    noRooms: "Aucune salle ouverte : crée la tienne et partage la page !",
    inLobby: (n) => `Dans le lobby (${n})`,
    join: "Rejoindre",
    roomOf: (n) => `Salle de ${n}`,
    host: "hôte",
    freeSeat: "Place libre",
    start: "Lancer la partie",
    leave: "Quitter",
    waitHost: "En attente du lancement par l'hôte…",
    needTwo: "Il faut au moins 2 joueurs pour lancer.",
    roomClosed: "L'hôte a fermé la salle.",
    rejoining: "Retour dans ta partie…",
    rejoined: "De retour dans la partie !",
    lateJoined: (n) => `${n} rejoint la partie et va rattraper son retard !`,
    rejoinFailed: "Impossible de retrouver ta partie.",
    invite: "Inviter",
    inviteSent: (n) => `Invitation envoyée à ${n}`,
    invitedBy: (n, a) => `${n} t'invite à jouer${a ? ` (${a})` : ""}`,
    ignore: "Ignorer",
    withCode: "Rejoindre avec un code",
    codePlaceholder: "Code de salle",
    joinCode: "Rejoindre",
    codeLabel: "Code de la salle",
    copyCode: "Copier",
    codeCopied: "Code copié !",
    codeNotFound: "Aucune salle ouverte avec ce code.",
    searching: "Recherche de la salle…",
    aloneHere: "Personne d'autre sur cette page pour l'instant. Envoie le lien à tes potes : ils apparaîtront ici avec un bouton Inviter.",
    copyLink: "Copier le lien",
    linkCopied: "Lien copié !",
    copyInvite: "Copier le lien d'invitation",
    inviteCopied: "Lien copié ! Envoie-le à tes potes.",
    joiningLink: "Connexion à la salle de ton lien…",
    linkGone: "Cette salle est pleine, déjà en partie ou fermée.",
    pickToJoin: "Choisis un pseudo pour rejoindre la salle.",
    hostPicks: "Tu es l'hôte : change d'anime ci-dessous, tout le monde suit.",
    hostChooses: "L'hôte choisit l'anime.",
    connecting: "Connexion au lobby…",
    offline: "Le jeu en ligne est indisponible pour l'instant.",
    you: "toi",
    taken: (n) => `${n} a déjà pris ce perso : relance gratuite !`,
    arcUsed: (arc) => `Arc : ${arc} (le plus bas de la salle, pour ne spoiler personne)`,
    lockedNote: (roles) => `Pas encore atteint à cet arc : ${roles}`,
    waitOthers: "En attente des autres joueurs…",
    yourTurn: "À ton tour !",
    turnOf: (n) => `Tour de ${n}…`,
    autoIn: (s) => `Jeu auto dans ${s} s`,
    skipped: "Aucune place libre ne convient : passé",
    finalRanking: "Classement final",
    youPlace: (n) => (n === 1 ? "Victoire !" : `Tu finis ${n}e`),
    left: "parti",
    tie: "Égalité en tête !",
    backRoom: "Retour à la salle",
    vs: "VS",
    pickName: "Choisis d'abord un pseudo",
    cards: "Cartes",
    back: "Retour",
    cTitle: "Mes cartes",
    cSub: "Tes cartes de boosters : ton inventaire avec ses doublons, les échanges avec tes amis et les duels de cartes de 2 à 8 joueurs.",
    cInventory: "Inventaire",
    cTrades: "Échanges",
    cDuels: "Duels",
    cUnique: "cartes différentes",
    cCopies: "cartes en tout",
    cDupes: "doublons",
    cGoBoosters: "Ouvrir des boosters",
    cNoCards: "Pas encore de carte : ouvre des boosters pour lancer ta collection.",
    cOnlyDupes: "Doublons seulement",
    cTradeThis: "Échanger cette carte",
    cRemove: "Retirer du deck",
    cTradeErr: { mine: "Tu n'as plus cette carte.", theirs: "Ton ami n'a plus cette carte.", gone: "Cette offre n'existe plus.", friend: "Tu ne peux échanger qu'avec tes amis.", card: "Carte invalide.", auth: "Crée un profil pour échanger." },
    cMakeProfile: "Créer mon profil",
    cNeedProfile: "Les échanges se font entre amis : crée un profil et ajoute tes amis d'abord.",
    cNewTrade: "Proposer un échange",
    cGot: (n) => `Offres reçues (${n})`,
    cNoneGot: "Aucune offre pour l'instant.",
    cAccept: "Accepter",
    cDecline: "Refuser",
    cTradeOk: "Échange fait ! Regarde ton inventaire.",
    cSent: (n) => `Offres envoyées (${n})`,
    cNoneSent: "Tu n'as envoyé aucune offre.",
    cCancel: "Annuler",
    cOfferFrom: (n) => `${n} te propose un échange`,
    cOfferTo: (n) => `Ton offre à ${n}`,
    cYouGet: "Tu reçois",
    cYouGive: "Tu donnes",
    cChange: "Changer",
    cStepFriend: "Ami",
    cStepGive: "Ta carte",
    cStepWant: "Sa carte",
    cGift: "Rien (un cadeau)",
    cPickFriend: "Avec qui veux-tu échanger ?",
    cNoFriends: "Pas encore d'ami : ajoutes-en dans ton profil (onglet Amis).",
    cPickGive: "Quelle carte donnes-tu ?",
    cPickGiveHelp: "Tes doublons d'abord : en donner un garde la carte dans ta collection.",
    cPickWant: (n) => `Quelle carte de ${n} veux-tu ?`,
    cNothing: "Rien, c'est un cadeau",
    cTheyHaveNone: "Cet ami n'a pas encore de carte.",
    cSend: "Envoyer l'offre",
    cSentOk: (n) => `Offre envoyée à ${n} !`,
    cInvitedBy: (n, m) => `${n} te défie en ${m}`,
    cPackBattle: "Bataille de boosters",
    cDeckBattle: "Bataille de decks",
    cPackHelp: "Chacun ouvre son booster du même anime à tour de rôle, trois fois : le booster le plus fort gagne la manche (puissance + rareté). Que la chance !",
    cDeckHelp: "Viens avec 5 cartes de ta collection et joue-en une par manche : puissance ×10, +8 si elle se transforme, + un lancer de dé. En 5 manches.",
    cDuelTitle: "Duels de cartes",
    cDuelHelp: "Bataille de boosters ou de decks, de 2 à 8 joueurs, seul ou en équipes. Chaque victoire rapporte un booster.",
    cNeedName: "Choisis un pseudo dans la barre en ligne pour jouer en ligne.",
    cCreate: "Créer un duel",
    cDeckFirst: "Construis d'abord ton deck de 5 cartes.",
    cNoDuels: "Aucun duel ouvert : crée le tien !",
    cAlone: "Personne d'autre sur la page des duels pour l'instant : une fois ton duel créé, invite un ami depuis ton profil.",
    cMyDeck: (a, b) => `Mon deck · ${a} / ${b}`,
    cDeckNeed: (n) => `Il te faut au moins ${n} cartes : ouvre des boosters !`,
    cDeckAuto: "Mes 5 plus fortes",
    cRound: (a, b) => `Manche ${a} / ${b}`,
    cOpening: "Ouverture…",
    cOpenMine: "Ouvrir",
    cYourPack: "À toi : ouvre ton booster !",
    cTheirPack: (n) => `${n} ouvre son booster…`,
    cRoundWon: "Manche gagnée !",
    cRoundLost: "Manche perdue",
    cRoundTie: "Égalité",
    cWaitDeck: "En attente de son deck…",
    cPlayCard: "Joue une carte",
    cPickPlay: "Choisis la carte que tu joues cette manche",
    cWaitPlay: (n) => `En attente de ${n}…`,
    cWin: "Victoire !",
    cWinForfeit: "Victoire : ton adversaire est parti",
    cLose: "Défaite",
    cDraw: "Égalité",
    cWinBooster: "+1 booster",
    cTeamsNote: "À partir de 3 joueurs, l'hôte peut séparer la salle en deux équipes : à chaque manche, l'équipe au plus gros total gagne.",
    cRoundShared: "Manche partagée !",
    cRoundBy: (n) => `Manche pour ${n}`,
  },
};
