// Crew Roll's interface text, in English and French.

export const T = {
  en: {
    title: "Crew Roll",
    sub: "Roll random characters and build the strongest crew. Every placement counts.",
    solo: "Solo",
    online: "Online",
    pick: "Anime",
    modeLabel: "Mode",
    arcLabel: "Arc",
    allArcs: "All arcs",
    roll: "Roll a character",
    draw: "Draw",
    waitingRoll: "Who joins the crew?",
    captainTag: "Leader",
    skip: "No slot left for this one: skip",
    tiers: { legend: "Legendary", epic: "Epic", common: "Common" },
    teamWins: (n) => `${n} wins!`,
    teamDraw: "Draw between the teams!",
    index: "Index",
    indexTitle: (a) => `${a} index`,
    indexSub: (n, arc) => `${n} cards${arc ? ` · spoiler-free up to ${arc}` : ""}. What each card scores in every role.`,
    indexSearch: "Search a character…",
    indexSort: "Sort",
    sortPower: "Power",
    sortName: "Name",
    allTiers: "All",
    bestRole: "Best role",
    noFit: "Can't go in this role",
    noCard: "No card matches.",
    newCard: "✨ New card!", collection: (a, b) => `Collection · ${a} / ${b}`, ownAll: "All", ownYes: "Drawn", ownNo: "To find", notDrawn: "Not drawn yet",
    ixTop: "Best crews",
    ixBoard: "Full leaderboard",
    ixNone: "No crew yet for this anime: build one in Solo!",
    ixTap: "Tap to see the transformation",
    rolling: "Rolling…",
    chooseSlot: "Choose a slot for this character",
    noSlot: "No free slot fits this character",
    reroll: (n) => `Reroll (${n} left)`,
    score: "Score",
    filled: (a, b) => `${a}/${b} slots`,
    power: "Power",
    spoiler: (arc) => `Spoiler-free up to: ${arc}`,
    spoilerAll: "All arcs (set your arc in the guessing game to limit spoilers)",
    resultTitle: "Your crew is complete!",
    best: "Best pick",
    worst: "Weakest pick",
    share: "Copy result",
    copied: "Result copied!",
    again: "New crew",
    empty: "Empty",
    lobbyTitle: "Lobby",
    lobbyHelp: "Create a room for 2 to 8 players, or join an open one. Players take turns: roll, place, and watch the others' picks live (3 rerolls each); the best crew wins.",
    yourName: "Your name",
    saveName: "Save",
    nameSaved: "Name saved",
    players: "Players",
    createRoom: "Create a room",
    openRooms: "Open rooms",
    noRooms: "No open room yet: create one and share the page!",
    inLobby: (n) => `In the lobby (${n})`,
    join: "Join",
    roomOf: (n) => `${n}'s room`,
    host: "host",
    freeSeat: "Free seat",
    start: "Start the match",
    leave: "Leave",
    waitHost: "Waiting for the host to start…",
    needTwo: "At least 2 players are needed to start.",
    roomClosed: "The host closed the room.",
    rejoining: "Getting you back into your match…",
    rejoined: "Back in the match!",
    lateJoined: (n) => `${n} joins the match and will catch up!`,
    rejoinFailed: "Your match couldn't be found anymore.",
    invite: "Invite",
    inviteSent: (n) => `Invitation sent to ${n}`,
    invitedBy: (n, a) => `${n} invites you to play${a ? ` (${a})` : ""}`,
    ignore: "Ignore",
    withCode: "Join with a code",
    codePlaceholder: "Room code",
    joinCode: "Join",
    codeLabel: "Room code",
    copyCode: "Copy",
    codeCopied: "Code copied!",
    codeNotFound: "No open room with this code.",
    searching: "Looking for the room…",
    aloneHere: "Nobody else is on this page yet. Send the link to your friends: they'll show up here with an Invite button.",
    copyLink: "Copy the link",
    linkCopied: "Link copied!",
    copyInvite: "Copy the invite link",
    inviteCopied: "Link copied! Send it to your friends.",
    joiningLink: "Joining the room from your link…",
    linkGone: "This room is full, already playing or closed.",
    pickToJoin: "Pick a name to join the room.",
    hostPicks: "You're the host: change the anime below, everyone follows.",
    hostChooses: "The host picks the anime.",
    connecting: "Connecting to the lobby…",
    offline: "Online play is unavailable right now.",
    you: "you",
    taken: (n) => `${n} already took this character: free roll!`,
    arcUsed: (arc) => `Arc: ${arc} (the lowest in the room, so nobody is spoiled)`,
    lockedNote: (roles) => `Not reached yet at this arc: ${roles}`,
    waitOthers: "Waiting for the other players…",
    yourTurn: "Your turn!",
    turnOf: (n) => `${n}'s turn…`,
    autoIn: (s) => `Auto-play in ${s} s`,
    skipped: "No free slot fits: skipped",
    finalRanking: "Final ranking",
    youPlace: (n) => (n === 1 ? "You win!" : `You finish #${n}`),
    left: "left",
    tie: "Tie for first!",
    backRoom: "Back to the room",
    vs: "VS",
    pickName: "Pick a name first",
  },
  fr: {
    title: "Roll ton équipage",
    sub: "Tire des personnages au hasard et construis l'équipage le plus fort. Chaque placement compte.",
    solo: "Solo",
    online: "En ligne",
    pick: "Anime",
    modeLabel: "Mode",
    arcLabel: "Arc",
    allArcs: "Tous les arcs",
    roll: "Tirer un personnage",
    draw: "Tirage",
    waitingRoll: "Qui rejoint l'équipage ?",
    captainTag: "Chef",
    skip: "Plus de place pour lui : passer",
    tiers: { legend: "Légendaire", epic: "Épique", common: "Commun" },
    teamWins: (n) => `${n} gagne !`,
    teamDraw: "Égalité entre les équipes !",
    index: "Index",
    indexTitle: (a) => `Index ${a}`,
    indexSub: (n, arc) => `${n} cartes${arc ? ` · sans spoiler jusqu'à ${arc}` : ""}. Ce que chaque carte rapporte dans chaque rôle.`,
    indexSearch: "Chercher un personnage…",
    indexSort: "Trier",
    sortPower: "Puissance",
    sortName: "Nom",
    allTiers: "Toutes",
    bestRole: "Meilleur rôle",
    noFit: "Ne peut pas aller à ce rôle",
    noCard: "Aucune carte ne correspond.",
    newCard: "✨ Nouvelle carte !", collection: (a, b) => `Collection · ${a} / ${b}`, ownAll: "Toutes", ownYes: "Tirées", ownNo: "À trouver", notDrawn: "Pas encore tirée",
    ixTop: "Meilleurs équipages",
    ixBoard: "Classement complet",
    ixNone: "Pas encore d'équipage pour cet animé : fais-en un en Solo !",
    ixTap: "Touche pour voir la transformation",
    rolling: "Tirage…",
    chooseSlot: "Choisis une place pour ce personnage",
    noSlot: "Aucune place libre ne convient à ce personnage",
    reroll: (n) => `Relancer (${n} restant${n > 1 ? "s" : ""})`,
    score: "Score",
    filled: (a, b) => `${a}/${b} places`,
    power: "Puissance",
    spoiler: (arc) => `Sans spoiler jusqu'à : ${arc}`,
    spoilerAll: "Tous les arcs (choisis ton arc dans le jeu de devinette pour limiter les spoilers)",
    resultTitle: "Ton équipage est complet !",
    best: "Meilleur choix",
    worst: "Choix le plus faible",
    share: "Copier le résultat",
    copied: "Résultat copié !",
    again: "Nouvel équipage",
    empty: "Libre",
    lobbyTitle: "Lobby",
    lobbyHelp: "Crée une salle de 2 à 8 joueurs, ou rejoins-en une. On joue chacun son tour : tire, place, et regarde les persos des autres en direct (3 relances chacun) : le meilleur équipage gagne.",
    yourName: "Ton pseudo",
    saveName: "OK",
    nameSaved: "Pseudo enregistré",
    players: "Joueurs",
    createRoom: "Créer une salle",
    openRooms: "Salles ouvertes",
    noRooms: "Aucune salle ouverte : crée la tienne et partage la page !",
    inLobby: (n) => `Dans le lobby (${n})`,
    join: "Rejoindre",
    roomOf: (n) => `Salle de ${n}`,
    host: "hôte",
    freeSeat: "Place libre",
    start: "Lancer la partie",
    leave: "Quitter",
    waitHost: "En attente du lancement par l'hôte…",
    needTwo: "Il faut au moins 2 joueurs pour lancer.",
    roomClosed: "L'hôte a fermé la salle.",
    rejoining: "Retour dans ta partie…",
    rejoined: "De retour dans la partie !",
    lateJoined: (n) => `${n} rejoint la partie et va rattraper son retard !`,
    rejoinFailed: "Impossible de retrouver ta partie.",
    invite: "Inviter",
    inviteSent: (n) => `Invitation envoyée à ${n}`,
    invitedBy: (n, a) => `${n} t'invite à jouer${a ? ` (${a})` : ""}`,
    ignore: "Ignorer",
    withCode: "Rejoindre avec un code",
    codePlaceholder: "Code de salle",
    joinCode: "Rejoindre",
    codeLabel: "Code de la salle",
    copyCode: "Copier",
    codeCopied: "Code copié !",
    codeNotFound: "Aucune salle ouverte avec ce code.",
    searching: "Recherche de la salle…",
    aloneHere: "Personne d'autre sur cette page pour l'instant. Envoie le lien à tes potes : ils apparaîtront ici avec un bouton Inviter.",
    copyLink: "Copier le lien",
    linkCopied: "Lien copié !",
    copyInvite: "Copier le lien d'invitation",
    inviteCopied: "Lien copié ! Envoie-le à tes potes.",
    joiningLink: "Connexion à la salle de ton lien…",
    linkGone: "Cette salle est pleine, déjà en partie ou fermée.",
    pickToJoin: "Choisis un pseudo pour rejoindre la salle.",
    hostPicks: "Tu es l'hôte : change d'anime ci-dessous, tout le monde suit.",
    hostChooses: "L'hôte choisit l'anime.",
    connecting: "Connexion au lobby…",
    offline: "Le jeu en ligne est indisponible pour l'instant.",
    you: "toi",
    taken: (n) => `${n} a déjà pris ce perso : relance gratuite !`,
    arcUsed: (arc) => `Arc : ${arc} (le plus bas de la salle, pour ne spoiler personne)`,
    lockedNote: (roles) => `Pas encore atteint à cet arc : ${roles}`,
    waitOthers: "En attente des autres joueurs…",
    yourTurn: "À ton tour !",
    turnOf: (n) => `Tour de ${n}…`,
    autoIn: (s) => `Jeu auto dans ${s} s`,
    skipped: "Aucune place libre ne convient : passé",
    finalRanking: "Classement final",
    youPlace: (n) => (n === 1 ? "Victoire !" : `Tu finis ${n}e`),
    left: "parti",
    tie: "Égalité en tête !",
    backRoom: "Retour à la salle",
    vs: "VS",
    pickName: "Choisis d'abord un pseudo",
  },
};
