// Crew Roll transformations: when one of these characters is drawn, the card powers up and turns
// into this form (portrait from crew/scripts/forms.mjs → crew/assets/forms/<game>-<id>.webp).
// arc: first arc where the form appears, so it never shows up before the player got there.
// fx: the effect's shape (aura: flames and lightning, pillar: a beam of energy, domain: a sphere
// that swallows the panel); c1/c2: its colours; kanji: the word slammed over the card.
// scene: a still of the moment (crew/assets/scenes/<game>-<id>.webp), animated in the cinematic when there is no clip.
(() => {
  const SAIYAN = { fx: "aura", c1: "255, 225, 77", c2: "255, 157, 46", kanji: "超", lightning: true };
  const BANKAI = { fx: "pillar", c1: "255, 42, 42", c2: "30, 6, 8", kanji: "卍解" };
  // A Quincy's Vollständig: wings of light and a halo.
  const QUINCY = { fx: "pillar", c1: "130, 210, 255", c2: "4, 10, 30", kanji: "滅却師" };
  const RESURRECCION = { fx: "pillar", c1: "60, 220, 140", c2: "10, 40, 25", kanji: "帰刃" };
  const DOMAIN = { fx: "domain", c1: "150, 90, 255", c2: "8, 4, 20", kanji: "領域展開" };
  // A Titan shifter's transformation: a lightning strike and a column of steam.
  // A fusion: two warriors become one in a blue and gold burst.
  const FUSION = { fx: "aura", c1: "90, 200, 255", c2: "255, 230, 120", kanji: "合体", lightning: true };
  const TITAN = { fx: "pillar", c1: "255, 196, 110", c2: "40, 14, 4", kanji: "巨人", lightning: true };

  window.CREW_FORMS = {
    dragonball: {
      goku: { arc: 5, name: { en: "Super Saiyan", fr: "Super Saiyan" }, ...SAIYAN },
      vegeta: { arc: 6, name: { en: "Super Saiyan", fr: "Super Saiyan" }, ...SAIYAN },
      gohan: { arc: 6, name: { en: "Super Saiyan 2", fr: "Super Saiyan 2" }, ...SAIYAN, lightning: true },
      "future-trunks": { arc: 6, name: { en: "Super Saiyan", fr: "Super Saiyan" }, ...SAIYAN },
      frieza: { arc: 8, name: { en: "Golden Frieza", fr: "Golden Freezer" }, fx: "aura", c1: "255, 211, 77", c2: "255, 245, 190", kanji: "金" },
      "goku-black": { arc: 8, name: { en: "Super Saiyan Rosé", fr: "Super Saiyan Rosé" }, fx: "aura", c1: "255, 122, 217", c2: "176, 77, 255", kanji: "超", lightning: true },
      cell: { arc: 6, name: { en: "Super Perfect Cell", fr: "Cell Super Parfait" }, fx: "aura", c1: "140, 255, 120", c2: "255, 230, 90", kanji: "完全体", lightning: true },
      "majin-buu": { arc: 7, name: { en: "Super Buu", fr: "Super Boo" }, fx: "pillar", c1: "255, 120, 200", c2: "40, 6, 30", kanji: "魔人" },
      piccolo: { arc: 8, name: { en: "Orange Piccolo", fr: "Piccolo Orange" }, fx: "aura", c1: "255, 150, 40", c2: "255, 90, 30", kanji: "覚醒" },
      jiren: { arc: 8, name: { en: "Full Power", fr: "Pleine puissance" }, fx: "aura", c1: "255, 60, 60", c2: "255, 200, 200", kanji: "全力", lightning: true },
      zamasu: { arc: 8, name: { en: "Fusion Zamasu", fr: "Zamasu fusionné" }, fx: "pillar", c1: "200, 255, 210", c2: "60, 10, 70", kanji: "合体" },
      kale: { arc: 8, name: { en: "Legendary Super Saiyan", fr: "Super Saiyan légendaire" }, fx: "aura", c1: "120, 255, 120", c2: "40, 180, 60", kanji: "伝説", lightning: true },
      "android-17": { arc: 8, name: { en: "Android Barrier", fr: "Barrière d'androïde" }, fx: "aura", c1: "120, 220, 255", c2: "40, 90, 200", kanji: "障壁" },
      beerus: { arc: 8, name: { en: "Hakai", fr: "Hakai" }, fx: "domain", c1: "190, 110, 255", c2: "10, 0, 20", kanji: "破壊", lightning: true },
      whis: { arc: 8, name: { en: "Ultra Instinct", fr: "Ultra Instinct" }, fx: "aura", c1: "200, 220, 255", c2: "120, 140, 220", kanji: "身勝手の極意" },
      champa: { arc: 8, name: { en: "Hakai", fr: "Hakai" }, fx: "domain", c1: "200, 120, 255", c2: "10, 0, 20", kanji: "破壊", lightning: true },
      vados: { arc: 8, name: { en: "Ultra Instinct", fr: "Ultra Instinct" }, fx: "aura", c1: "180, 210, 255", c2: "90, 90, 200", kanji: "身勝手の極意" },
      zeno: { arc: 8, name: { en: "Erasure", fr: "Effacement" }, fx: "domain", c1: "255, 255, 255", c2: "30, 10, 60", kanji: "消滅", lightning: true },
      "grand-priest": { arc: 8, name: { en: "Ultra Instinct", fr: "Ultra Instinct" }, fx: "aura", c1: "210, 230, 255", c2: "100, 120, 210", kanji: "大神官" },
      vegito: { arc: 8, name: { en: "Potara fusion · Super Saiyan Blue", fr: "Fusion Potara · Super Saiyan Blue" }, ...FUSION },
      gogeta: { focus: "62% 20%", arc: 8, name: { en: "Fusion dance · Super Saiyan Blue", fr: "Danse de fusion · Super Saiyan Blue" }, ...FUSION },
      kefla: { arc: 8, name: { en: "Potara fusion · Super Saiyan 2", fr: "Fusion Potara · Super Saiyan 2" }, ...FUSION, c1: "140, 255, 120" },
      broly: { arc: 8, name: { en: "Legendary Super Saiyan", fr: "Super Saiyan légendaire" }, fx: "aura", c1: "140, 255, 90", c2: "255, 240, 120", kanji: "伝説", lightning: true },
    },
    bleach: {
      "rukia-kuchiki": { arc: 6, name: { en: "Bankai · Hakka no Togame", fr: "Bankai · Hakka no Togame" }, fx: "pillar", c1: "200, 240, 255", c2: "8, 16, 40", kanji: "白霞罸" },
      "kaname-tosen": { arc: 4, name: { en: "Resurrección · Grillar Grillo", fr: "Resurrección · Grillar Grillo" }, ...RESURRECCION, c1: "170, 130, 255", kanji: "清虫百式" },
      "tier-harribel": { arc: 4, name: { en: "Resurrección · Tiburón", fr: "Resurrección · Tiburón" }, ...RESURRECCION, c1: "255, 220, 120", kanji: "皇鮫后" },
      "nelliel-tu-odelschwanck": { arc: 3, name: { en: "Resurrección · Gamuza", fr: "Resurrección · Gamuza" }, ...RESURRECCION, kanji: "羚騎士" },
      "uryu-ishida": { arc: 1, name: { en: "Letzt Stil", fr: "Letzt Stil" }, ...QUINCY },
      "askin-nakk-le-vaar": { arc: 6, name: { en: "Vollständig · Gift Ball Deluxe", fr: "Vollständig · Gift Ball Deluxe" }, ...QUINCY, c1: "190, 110, 255" },
      "bambietta-basterbine": { arc: 6, name: { en: "Vollständig · Calaveras", fr: "Vollständig · Calaveras" }, ...QUINCY, c1: "255, 90, 110" },
      "liltotto-lamperd": { arc: 6, name: { en: "Vollständig · Gagael", fr: "Vollständig · Gagael" }, ...QUINCY, c1: "255, 230, 90" },
      "as-nodt": { arc: 6, name: { en: "Vollständig · Tatarforas", fr: "Vollständig · Tatarforas" }, ...QUINCY, c1: "170, 90, 255" },
      "lille-barro": { arc: 6, name: { en: "Vollständig · Jilliel", fr: "Vollständig · Jilliel" }, ...QUINCY, c1: "255, 210, 90" },
      "gremmy-thoumeaux": { arc: 6, name: { en: "The Visionary", fr: "L'Imagination" }, ...QUINCY, c1: "255, 80, 120" },
      "jugram-haschwalth": { arc: 6, name: { en: "The Balance", fr: "L'Équilibre" }, ...QUINCY },
      "bazz-b": { arc: 6, name: { en: "Burner Finger", fr: "Burner Finger" }, ...QUINCY, c1: "255, 120, 40" },
      "kirio-hikifune": { arc: 6, name: { en: "Slim form", fr: "Forme affinée" }, fx: "aura", c1: "255, 170, 210", c2: "60, 10, 30", kanji: "麒麟殿" },
      "ichigo-kurosaki": { arc: 1, name: { en: "Bankai · Tensa Zangetsu", fr: "Bankai · Tensa Zangetsu" }, ...BANKAI , next: { arc: 4, name: { en: "Final Getsuga Tenshō", fr: "Getsuga Tenshô final" }, fx: "pillar", c1: "200, 20, 30", c2: "6, 0, 2", kanji: "無月", clip: false } },
      "byakuya-kuchiki": { arc: 1, name: { en: "Bankai · Senbonzakura Kageyoshi", fr: "Bankai · Senbonzakura Kageyoshi" }, ...BANKAI, c1: "255, 140, 190" , next: { arc: 6, name: { en: "Bankai · Senbonzakura Kageyoshi", fr: "Bankai · Senbonzakura Kageyoshi" }, clip: true } },
      "renji-abarai": { arc: 1, name: { en: "Bankai · Hihiō Zabimaru", fr: "Bankai · Hihiō Zabimaru" }, ...BANKAI },
      "toshiro-hitsugaya": { arc: 1, name: { en: "Bankai · Daiguren Hyōrinmaru", fr: "Bankai · Daiguren Hyōrinmaru" }, ...BANKAI, c1: "120, 210, 255", c2: "6, 20, 40" },
      "ulquiorra-cifer": { arc: 3, name: { en: "Resurrección · Segunda Etapa", fr: "Resurrección · Segunda Etapa" }, ...RESURRECCION },
      "grimmjow-jaegerjaquez": { arc: 3, name: { en: "Resurrección · Pantera", fr: "Resurrección · Pantera" }, ...RESURRECCION, c1: "80, 200, 255", c2: "6, 20, 40" },
      "barragan-louisenbairn": { arc: 4, name: { en: "Resurrección · Arrogante", fr: "Resurrección · Arrogante" }, ...RESURRECCION, c1: "170, 90, 255", c2: "16, 4, 24", kanji: "老い" },
      "coyote-starrk": { arc: 4, name: { en: "Resurrección · Los Lobos", fr: "Resurrección · Los Lobos" }, ...RESURRECCION, c1: "120, 200, 255", c2: "6, 16, 40" },
      "sajin-komamura": { focus: "25% 30%", arc: 1, name: { en: "Bankai · Kokujō Tengen Myō'ō", fr: "Bankai · Kokujō Tengen Myō'ō" }, ...BANKAI, c1: "255, 120, 40" },
      "mayuri-kurotsuchi": { arc: 1, name: { en: "Bankai · Konjiki Ashisogi Jizō", fr: "Bankai · Konjiki Ashisogi Jizō" }, ...BANKAI, c1: "255, 210, 60", c2: "40, 6, 40" },
      "sosuke-aizen": { arc: 4, name: { en: "Fused with the Hōgyoku", fr: "Fusion avec le Hōgyoku" }, fx: "domain", c1: "190, 120, 255", c2: "10, 4, 24", kanji: "崩玉" },
      "kenpachi-zaraki": { arc: 6, name: { en: "Bankai", fr: "Bankai" }, ...BANKAI, kanji: "卍解", lightning: true },
      yhwach: { arc: 6, name: { en: "The Almighty", fr: "The Almighty" }, fx: "domain", c1: "255, 40, 50", c2: "4, 4, 12", kanji: "全知全能" },
      "genryusai-yamamoto": { focus: "8% 20%", arc: 6, name: { en: "Bankai · Zanka no Tachi", fr: "Bankai · Zanka no Tachi" }, fx: "pillar", c1: "255, 120, 30", c2: "40, 6, 0", kanji: "残火の太刀" },
      "ichibe-hyosube": { arc: 6, name: { en: "Ichimonji · Shirafude", fr: "Ichimonji · Shirafude" }, fx: "domain", c1: "240, 240, 240", c2: "4, 4, 6", kanji: "一文字" },
    },
    naruto: {
      "naruto-uzumaki": { arc: 6, name: { en: "Sage Mode", fr: "Mode Ermite" }, fx: "aura", c1: "255, 150, 40", c2: "255, 220, 90", kanji: "仙人" },
      "sasuke-uchiha": { arc: 7, name: { en: "Susanoo", fr: "Susanoo" }, fx: "pillar", c1: "180, 110, 255", c2: "20, 6, 40", kanji: "須佐能乎" },
      "itachi-uchiha": { arc: 6, name: { en: "Susanoo", fr: "Susanoo" }, fx: "pillar", c1: "255, 90, 50", c2: "40, 6, 6", kanji: "須佐能乎" },
      "kakashi-hatake": { arc: 4, name: { en: "Mangekyō Sharingan", fr: "Mangekyō Sharingan" }, fx: "domain", c1: "230, 30, 40", c2: "20, 0, 0", kanji: "万華鏡" },
      "might-guy": { arc: 8, name: { en: "Eight Gates", fr: "Huit Portes" }, fx: "aura", c1: "255, 60, 60", c2: "90, 255, 140", kanji: "八門遁甲", lightning: true },
      "rock-lee": { arc: 1, name: { en: "Eight Gates", fr: "Huit Portes" }, fx: "aura", c1: "90, 255, 140", c2: "60, 160, 255", kanji: "八門遁甲" },
      gaara: { arc: 2, name: { en: "Shukaku", fr: "Shukaku" }, fx: "pillar", c1: "230, 200, 140", c2: "50, 30, 10", kanji: "守鶴" },
      jiraiya: { arc: 6, name: { en: "Sage Mode", fr: "Mode Ermite" }, fx: "aura", c1: "255, 150, 40", c2: "255, 220, 90", kanji: "仙人" },
      "kabuto-yakushi": { arc: 8, name: { en: "Sage Mode", fr: "Mode Ermite" }, fx: "aura", c1: "120, 220, 255", c2: "60, 90, 200", kanji: "仙人" },
      "minato-namikaze": { arc: 8, name: { en: "Nine-Tails Chakra Mode", fr: "Mode Chakra de Kyûbi" }, fx: "aura", c1: "255, 170, 40", c2: "255, 240, 140", kanji: "九尾", lightning: true },
      "obito-uchiha": { arc: 8, name: { en: "Ten-Tails Jinchūriki", fr: "Jinchûriki de Jûbi" }, fx: "pillar", c1: "240, 240, 230", c2: "20, 10, 30", kanji: "十尾" },
      "madara-uchiha": { arc: 8, name: { en: "Six Paths Sage Mode", fr: "Mode Ermite des Six Chemins" }, fx: "domain", c1: "235, 235, 255", c2: "10, 6, 20", kanji: "六道" },
      "hashirama-senju": { arc: 8, name: { en: "Sage Mode", fr: "Mode Ermite" }, fx: "aura", c1: "120, 230, 120", c2: "30, 80, 30", kanji: "仙人" },
      "kaguya-otsutsuki": { arc: 8, name: { en: "Rabbit Goddess", fr: "Déesse Lapin" }, fx: "domain", c1: "235, 235, 255", c2: "20, 10, 40", kanji: "輪廻写輪眼", lightning: true },
      "hagoromo-otsutsuki": { arc: 8, name: { en: "Sage of Six Paths", fr: "Ermite Rikudô" }, fx: "pillar", c1: "200, 160, 255", c2: "20, 10, 40", kanji: "六道" },
    },
    onepiece: {
      "rocks-d-xebec": { arc: 9, name: { en: "Conqueror's Haki · God Valley", fr: "Haki des rois · God Valley" }, fx: "aura", c1: "255, 50, 70", c2: "20, 0, 6", kanji: "覇王色", lightning: true },
      aramaki: { arc: 9, name: { en: "Logia · Forest", fr: "Logia · Forêt" }, fx: "domain", c1: "120, 230, 110", c2: "6, 24, 6", kanji: "森" },
      "monkey-d-luffy": { arc: 9, name: { en: "Gear 5", fr: "Gear 5" }, fx: "aura", c1: "255, 255, 255", c2: "190, 150, 255", kanji: "ニカ", lightning: true },
      "roronoa-zoro": { arc: 3, name: { en: "Asura", fr: "Asura" }, fx: "domain", c1: "90, 255, 150", c2: "4, 20, 10", kanji: "阿修羅" },
      "tony-tony-chopper": { arc: 3, name: { en: "Monster Point", fr: "Monster Point" }, fx: "pillar", c1: "255, 120, 160", c2: "40, 10, 10", kanji: "怪物" },
      "polo-marco": { arc: 5, name: { en: "Phoenix", fr: "Phénix" }, fx: "aura", c1: "80, 200, 255", c2: "255, 220, 80", kanji: "不死鳥" },
      "rob-lucci": { arc: 3, name: { en: "Leopard Human-Beast form", fr: "Forme hybride du Léopard" }, fx: "aura", c1: "255, 200, 60", c2: "60, 30, 0", kanji: "豹", lightning: true,
        // Egghead: awakened, against Luffy in Gear 5 (the clash of their fists opens the cinematic: scenes/<game>-<id>-2.webp).
        next: { arc: 10, name: { en: "Awakening · Leopard", fr: "Éveil · Léopard" }, fx: "aura", c1: "120, 150, 255", c2: "30, 10, 60", kanji: "覚醒", lightning: true, scene: true, clip: true } },
      magellan: { arc: 5, name: { en: "Venom Demon: Hell's Judgement", fr: "Démon du venin : Jugement des enfers" }, fx: "pillar", c1: "200, 60, 255", c2: "30, 0, 30", kanji: "毒" },
      // The admirals' Logia: magma, ice, light.
      sakazuki: { arc: 5, name: { en: "Logia · Magma", fr: "Logia · Magma" }, fx: "pillar", c1: "255, 90, 30", c2: "40, 6, 0", kanji: "冥狗", lightning: true },
      kuzan: { arc: 3, name: { en: "Logia · Ice Age", fr: "Logia · Âge de glace" }, fx: "domain", c1: "150, 220, 255", c2: "4, 14, 30", kanji: "氷河時代" },
      borsalino: { arc: 5, name: { en: "Logia · Light", fr: "Logia · Lumière" }, fx: "aura", c1: "255, 230, 90", c2: "255, 255, 220", kanji: "光", lightning: true },
      imu: { arc: 10, name: { en: "True form", fr: "Vraie forme" }, fx: "domain", c1: "200, 40, 60", c2: "6, 0, 8", kanji: "虚" },
      king: { arc: 9, name: { en: "Pteranodon", fr: "Ptéranodon" }, fx: "pillar", c1: "255, 110, 30", c2: "30, 6, 20", kanji: "火災" },
      sanji: { arc: 8, name: { en: "Raid Suit · Stealth Black", fr: "Raid Suit · Stealth Black" }, fx: "aura", c1: "255, 120, 40", c2: "255, 40, 40", kanji: "黒足" },
      "charlotte-katakuri": { arc: 8, name: { en: "Future Sight", fr: "Haki de l'observation · Futur" }, fx: "domain", c1: "255, 90, 140", c2: "20, 4, 12", kanji: "見聞色" },
      kaidou: { arc: 9, name: { en: "Azure Dragon", fr: "Dragon azur" }, fx: "pillar", c1: "90, 160, 255", c2: "6, 12, 40", kanji: "龍", lightning: true },
      shanks: { arc: 9, name: { en: "Divine Departure", fr: "Kamusari" }, fx: "aura", c1: "255, 60, 60", c2: "20, 0, 0", kanji: "覇王色", lightning: true },
      "monkey-d-dragon": { arc: 0, name: { en: "The storm", fr: "La tempête" }, fx: "pillar", c1: "150, 200, 255", c2: "10, 20, 40", kanji: "嵐", lightning: true },
      "gol-d-roger": { arc: 9, name: { en: "Divine Departure", fr: "Kamusari" }, fx: "aura", c1: "255, 60, 60", c2: "20, 0, 0", kanji: "神避", lightning: true, focus: "88% 15%" },
      "dracule-mihawk": { arc: 5, name: { en: "Black Blade Yoru", fr: "Lame noire Yoru" }, fx: "pillar", c1: "120, 255, 160", c2: "0, 20, 10", kanji: "黒刀" },
      "marshall-d-teach": { arc: 5, name: { en: "Darkness and Tremors", fr: "Ténèbres et séismes" }, fx: "domain", c1: "120, 40, 160", c2: "0, 0, 0", kanji: "闇" },
      "monkey-d-garp": { arc: 10, name: { en: "Galaxy Impact", fr: "Galaxy Impact" }, fx: "aura", c1: "255, 230, 120", c2: "40, 20, 0", kanji: "拳骨", lightning: true },
      "silvers-rayleigh": { focus: "68% 40%", arc: 5, name: { en: "Conqueror's Haki", fr: "Haki des rois" }, fx: "aura", c1: "255, 60, 60", c2: "20, 0, 0", kanji: "覇王色", lightning: true },
      "edward-newgate": { arc: 5, name: { en: "Tremors", fr: "Séismes" }, fx: "pillar", c1: "220, 240, 255", c2: "20, 30, 50", kanji: "震", lightning: true },
      sengoku: { arc: 5, name: { en: "Great Buddha", fr: "Grand Bouddha" }, fx: "pillar", c1: "255, 215, 90", c2: "60, 40, 0", kanji: "大仏" },
      issho: { arc: 7, name: { en: "Gravity Blade", fr: "Lame gravitationnelle" }, fx: "domain", c1: "190, 120, 255", c2: "6, 0, 14", kanji: "重力刀" },
      "charlotte-linlin": { arc: 8, name: { en: "Prometheus and Zeus", fr: "Prometheus et Zeus" }, fx: "aura", c1: "255, 140, 60", c2: "255, 230, 120", kanji: "魂", lightning: true },
      "kouzuki-oden": { focus: "25% 55%", arc: 9, name: { en: "Togen Totsuka", fr: "Togen Totsuka" }, fx: "pillar", c1: "120, 220, 255", c2: "0, 20, 40", kanji: "桃源十拳" },
      "scopper-gaban": { arc: 9, name: { en: "Roger's right hand", fr: "Bras droit de Roger" }, fx: "aura", c1: "255, 190, 90", c2: "60, 30, 0", kanji: "覇気" },
      "figarland-garling": { arc: 10, name: { en: "Holy Knight's immortality", fr: "Immortalité du Chevalier sacré" }, fx: "domain", c1: "220, 30, 50", c2: "6, 0, 4", kanji: "神の騎士" },
    },
    jujutsukaisen: {
      "satoru-gojo": { focus: "35% 30%", arc: 1, name: { en: "Domain Expansion · Infinite Void", fr: "Extension du territoire · Sphère de l'espace infini" }, ...DOMAIN, c1: "90, 170, 255" },
      "ryomen-sukuna": { arc: 5, name: { en: "Domain Expansion · Malevolent Shrine", fr: "Extension du territoire · Temple maléfique" }, ...DOMAIN, c1: "255, 50, 60" },
      "yuta-okkotsu": { arc: 6, name: { en: "Rika, fully manifested", fr: "Rika, pleinement manifestée" }, fx: "pillar", c1: "255, 70, 120", c2: "20, 0, 10", kanji: "里香" },
      mahito: { arc: 1, name: { en: "Domain Expansion · Self-Embodiment of Perfection", fr: "Extension du territoire · Incarnation parfaite" }, ...DOMAIN, c1: "255, 120, 60" },
      jogo: { arc: 1, name: { en: "Domain Expansion · Coffin of the Iron Mountain", fr: "Extension du territoire · Cercueil de la montagne de fer" }, ...DOMAIN, c1: "255, 110, 40" },
      "megumi-fushiguro": { arc: 3, name: { en: "Domain Expansion · Chimera Shadow Garden", fr: "Extension du territoire · Jardin des ombres chimériques" }, ...DOMAIN, c1: "70, 140, 255" },
      "maki-zen-in": { focus: "30% 25%", arc: 6, name: { en: "Heavenly Restriction awakened", fr: "Entrave céleste éveillée" }, fx: "aura", c1: "120, 255, 160", c2: "255, 255, 255", kanji: "天与呪縛" },
      "kinji-hakari": { arc: 6, name: { en: "Jackpot", fr: "Jackpot" }, fx: "aura", c1: "90, 230, 255", c2: "255, 90, 200", kanji: "大当たり", lightning: true },
      "hiromi-higuruma": { arc: 6, name: { en: "Domain Expansion · Deadly Sentencing", fr: "Extension du territoire · Jugement mortel" }, ...DOMAIN, c1: "60, 230, 170" },
      "aoi-todo": { arc: 2, name: { en: "Boogie Woogie", fr: "Boogie Woogie" }, fx: "aura", c1: "120, 160, 255", c2: "10, 10, 40", kanji: "不義遊戯", lightning: true },
      "toji-fushiguro": { arc: 4, name: { en: "Heavenly Restriction", fr: "Restriction céleste" }, fx: "aura", c1: "140, 255, 140", c2: "10, 30, 10", kanji: "天与呪縛" },
      "yuki-tsukumo": { arc: 6, name: { en: "Star Rage", fr: "Star Rage" }, fx: "domain", c1: "255, 220, 120", c2: "10, 6, 30", kanji: "星の怒り", lightning: true },
    },
    hunterxhunter: {
      "killua-zoldyck": { arc: 5, name: { en: "Godspeed", fr: "Vitesse divine" }, fx: "aura", c1: "140, 220, 255", c2: "255, 255, 255", kanji: "神速", lightning: true },
      // Gon's vow against Pitou: he forces his body to the age it would need to win.
      "gon-freecss": { arc: 5, name: { en: "Adult Gon", fr: "Gon adulte" }, fx: "pillar", c1: "255, 170, 50", c2: "30, 10, 0", kanji: "制約", lightning: true },
      kurapika: { arc: 3, name: { en: "Emperor Time", fr: "Emperor Time" }, fx: "domain", c1: "255, 40, 50", c2: "20, 0, 0", kanji: "絶対時間" },
      "biscuit-krueger": { arc: 4, name: { en: "True Form", fr: "Vraie forme" }, fx: "aura", c1: "255, 140, 200", c2: "255, 230, 120", kanji: "真体" },
      "isaac-netero": { arc: 5, name: { en: "Hundred-Type Guanyin Bodhisattva", fr: "Bodhisattva aux cent mille mains" }, fx: "pillar", c1: "255, 210, 80", c2: "40, 20, 0", kanji: "百式観音" },
      neferpitou: { arc: 5, name: { en: "Terpsichora", fr: "Terpsichora" }, fx: "aura", c1: "255, 50, 70", c2: "60, 0, 20", kanji: "黒子舞想", lightning: true },
      menthuthuyoupi: { arc: 5, name: { en: "Rage form", fr: "Forme de rage" }, fx: "pillar", c1: "255, 60, 60", c2: "30, 0, 0", kanji: "憤怒" },
      "zeno-zoldyck": { arc: 5, name: { en: "Dragon Dive", fr: "Dragon Dive" }, fx: "aura", c1: "120, 200, 255", c2: "20, 60, 140", kanji: "龍頭戯画", lightning: true },
      "chrollo-lucilfer": { arc: 3, name: { en: "Skill Hunter", fr: "Skill Hunter" }, fx: "domain", c1: "190, 150, 255", c2: "10, 4, 20", kanji: "盗賊の極意" },
      meruem: { arc: 5, name: { en: "Aura Synthesis", fr: "Synthèse d'aura" }, fx: "aura", c1: "120, 255, 200", c2: "30, 90, 120", kanji: "王", lightning: true },
      "ging-freecss": { arc: 6, name: { en: "Nen release", fr: "Libération du Nen" }, fx: "aura", c1: "255, 210, 90", c2: "120, 70, 20", kanji: "念" },
      "alluka-zoldyck": { arc: 6, name: { en: "Nanika", fr: "Nanika" }, fx: "domain", c1: "40, 40, 50", c2: "0, 0, 0", kanji: "何か" },
    },
    blackclover: {
      // Devils: their hosts reach 100% Devil Union, the devils themselves fully manifest.
      asta: { arc: 9, name: { en: "Devil Union · Liebe", fr: "Union démoniaque · Liebe" }, fx: "aura", c1: "255, 40, 60", c2: "20, 0, 6", kanji: "悪魔同化", lightning: true },
      liebe: { arc: 7, name: { en: "Devil form", fr: "Forme démoniaque" }, fx: "pillar", c1: "255, 50, 70", c2: "10, 0, 4", kanji: "悪魔" },
      zagred: { arc: 7, name: { en: "Full manifestation", fr: "Manifestation complète" }, fx: "domain", c1: "200, 60, 255", c2: "8, 0, 16", kanji: "言霊" },
      megicula: { arc: 9, name: { en: "Full manifestation", fr: "Manifestation complète" }, fx: "domain", c1: "255, 70, 120", c2: "20, 0, 10", kanji: "呪" },
      lucifero: { arc: 9, name: { en: "Descent of Lucifero", fr: "Descente de Lucifero" }, fx: "pillar", c1: "190, 120, 255", c2: "4, 0, 10", kanji: "重力", lightning: true },
      "vanica-zogratis": { arc: 9, name: { en: "Devil Union · 100%", fr: "Union démoniaque · 100 %" }, fx: "domain", c1: "255, 60, 90", c2: "20, 0, 8", kanji: "悪魔同化" },
      "zenon-zogratis": { arc: 9, name: { en: "Devil Union · 100%", fr: "Union démoniaque · 100 %" }, fx: "pillar", c1: "230, 230, 240", c2: "10, 10, 16", kanji: "悪魔同化" },
      "nacht-faust": { arc: 9, name: { en: "Gallus × Felis × Canis", fr: "Gallus × Felis × Canis" }, fx: "aura", c1: "140, 90, 255", c2: "20, 0, 30", kanji: "悪魔同化", lightning: true },
      yuno: { arc: 7, name: { en: "Spirit Dive", fr: "Spirit Dive" }, fx: "aura", c1: "120, 255, 170", c2: "255, 255, 255", kanji: "精霊同化" },
      "fuegoleon-vermillion": { focus: "72% 35%", arc: 7, name: { en: "Salamander", fr: "Salamandre" }, fx: "pillar", c1: "255, 120, 30", c2: "50, 10, 0", kanji: "火精" },
      "noelle-silva": { arc: 9, name: { en: "Valkyrie Dress", fr: "Armure de Valkyrie" }, fx: "aura", c1: "110, 220, 255", c2: "200, 255, 240", kanji: "戦乙女" },
      "dante-zogratis": { arc: 9, name: { en: "Devil Union · 100%", fr: "Union démoniaque · 100 %" }, fx: "domain", c1: "160, 60, 255", c2: "10, 0, 20", kanji: "悪魔同化" },
      "yami-sukehiro": { arc: 2, name: { en: "Dark Cloaked Dimension Slash", fr: "Lame de ténèbres : Fendeur de dimensions" }, fx: "pillar", c1: "150, 90, 220", c2: "0, 0, 0", kanji: "闇纏・次元斬り", lightning: true },
      "mereoleona-vermillion": { arc: 4, name: { en: "Calidus Brachium", fr: "Calidus Brachium" }, fx: "pillar", c1: "255, 110, 30", c2: "50, 6, 0", kanji: "炎" },
      "julius-novachrono": { arc: 6, name: { en: "Time Magic", fr: "Magie du temps" }, fx: "domain", c1: "255, 220, 120", c2: "20, 14, 4", kanji: "時間" },
      licht: { arc: 7, name: { en: "Sword of Despair", fr: "Épée du désespoir" }, fx: "pillar", c1: "220, 255, 220", c2: "10, 20, 10", kanji: "剣", lightning: true },
      "lucius-zogratis": { arc: 9, name: { en: "Soul Magic · Chrono Stasis", fr: "Magie de l'âme · Chrono Stasis" }, fx: "domain", c1: "255, 230, 160", c2: "10, 6, 2", kanji: "魂", lightning: true },
    },
    // Each shifter transforms only from the arc where the anime reveals who they are.
    attackontitan: {
      "eren-yeager": { arc: 0, name: { en: "Attack Titan", fr: "Titan Assaillant" }, ...TITAN },
      "annie-leonhart": { arc: 1, name: { en: "Female Titan", fr: "Titan Féminin" }, ...TITAN, c1: "170, 220, 255" },
      "reiner-braun": { arc: 2, name: { en: "Armored Titan", fr: "Titan Cuirassé" }, ...TITAN, c1: "255, 230, 170" },
      "bertholdt-hoover": { arc: 2, name: { en: "Colossal Titan", fr: "Titan Colossal" }, ...TITAN, c1: "255, 90, 40" },
      ymir: { arc: 2, name: { en: "Jaw Titan", fr: "Titan Mâchoire" }, ...TITAN },
      "armin-arlert": { arc: 4, name: { en: "Colossal Titan", fr: "Titan Colossal" }, ...TITAN, c1: "255, 90, 40" },
      "zeke-yeager": { arc: 4, name: { en: "Beast Titan", fr: "Titan Bestial" }, ...TITAN, c1: "230, 200, 140" },
      "porco-galliard": { arc: 5, name: { en: "Jaw Titan", fr: "Titan Mâchoire" }, ...TITAN },
      "pieck-finger": { arc: 5, name: { en: "Cart Titan", fr: "Titan Charrette" }, ...TITAN },
      "lara-tybur": { arc: 5, name: { en: "War Hammer Titan", fr: "Titan Marteau d'armes" }, ...TITAN, c1: "255, 240, 220" },
      "falco-grice": { arc: 6, name: { en: "Jaw Titan", fr: "Titan Mâchoire" }, ...TITAN },
      "rod-reiss": { arc: 3, name: { en: "Abnormal Titan", fr: "Titan déviant" }, ...TITAN, c1: "255, 150, 80" },
      "dina-fritz": { arc: 4, name: { en: "Smiling Titan", fr: "Titan souriant" }, ...TITAN, c1: "255, 200, 150" },
      "grisha-yeager": { arc: 4, name: { en: "Attack Titan", fr: "Titan Assaillant" }, ...TITAN },
      "marcel-galliard": { arc: 4, name: { en: "Jaw Titan", fr: "Titan Mâchoire" }, ...TITAN },
      "ymir-fritz": { arc: 6, name: { en: "Founding Titan", fr: "Titan Originel" }, ...TITAN, c1: "255, 240, 200" },
      levi: { arc: 4, name: { en: "Ackerman awakening", fr: "Éveil Ackerman" }, fx: "aura", c1: "200, 230, 255", c2: "20, 30, 40", kanji: "人類最強" },
    },
    // ── The six anime added in October 2026 (moves for those without a transformation) ──
    demonslayer: {
      "zenitsu-agatsuma": { arc: 4, name: { en: "Thunderclap and Flash · Godspeed", fr: "Éclair foudroyant · Vitesse divine" }, fx: "aura", c1: "255, 220, 60", c2: "255, 255, 210", kanji: "雷", lightning: true },
      akaza: { arc: 3, name: { en: "Destructive Death · Compass Needle", fr: "Mort destructrice · Aiguille de boussole" }, fx: "domain", c1: "90, 180, 255", c2: "255, 60, 130", kanji: "破壊殺" },
      "kyojuro-rengoku": { arc: 3, name: { en: "Ninth Form · Rengoku", fr: "Neuvième forme · Rengoku" }, fx: "pillar", c1: "255, 110, 30", c2: "60, 12, 0", kanji: "炎" },
      "tanjiro-kamado": { arc: 2, name: { en: "Hinokami Kagura · Dance", fr: "Hinokami Kagura · Danse" }, fx: "aura", c1: "255, 120, 40", c2: "255, 220, 120", kanji: "日の呼吸" },
      "gyomei-himejima": { arc: 6, name: { en: "Stone Breathing · Demon Slayer Mark", fr: "Souffle de la pierre · Marque du pourfendeur" }, fx: "aura", c1: "200, 200, 210", c2: "40, 30, 20", kanji: "岩", lightning: true },
      "yoriichi-tsugikuni": { arc: 5, name: { en: "Sun Breathing", fr: "Souffle du soleil" }, fx: "pillar", c1: "255, 140, 40", c2: "60, 10, 0", kanji: "日の呼吸" },
      "muzan-kibutsuji": { arc: 6, name: { en: "True form", fr: "Forme véritable" }, fx: "domain", c1: "200, 20, 40", c2: "6, 0, 4", kanji: "鬼舞辻", lightning: true },
      kokushibo: { arc: 5, name: { en: "Moon Breathing", fr: "Souffle de la lune" }, fx: "domain", c1: "170, 120, 255", c2: "6, 2, 18", kanji: "月の呼吸" },
      doma: { focus: "75% 30%", arc: 7, name: { en: "Blood Demon Art · Frozen Lotus", fr: "Art démoniaque · Lotus gelé" }, fx: "domain", c1: "170, 230, 255", c2: "4, 12, 30", kanji: "血鬼術" },
    },
    myheroacademia: {
      "katsuki-bakugo": { arc: 1, name: { en: "Howitzer Impact", fr: "Howitzer Impact" }, fx: "aura", c1: "255, 170, 60", c2: "255, 80, 20", kanji: "爆", lightning: true },
      dabi: { arc: 7, name: { en: "Dabi's Dance", fr: "La danse de Dabi" }, fx: "pillar", c1: "80, 160, 255", c2: "10, 20, 60", kanji: "荼毘" },
      "shoto-todoroki": { arc: 1, name: { en: "Half-Cold Half-Hot · Flames unleashed", fr: "Glace et feu · Flammes libérées" }, fx: "pillar", c1: "255, 100, 40", c2: "120, 200, 255", kanji: "氷炎" },
      "izuku-midoriya": { arc: 2, name: { en: "One For All · Full Cowl", fr: "One For All · Full Cowl" }, fx: "aura", c1: "120, 255, 140", c2: "20, 120, 60", kanji: "ワン・フォー・オール", lightning: true },
      "all-might": { arc: 3, name: { en: "United States of Smash", fr: "United States of Smash" }, fx: "aura", c1: "255, 220, 60", c2: "40, 60, 200", kanji: "平和の象徴", lightning: true },
      endeavor: { arc: 6, name: { en: "Plus Ultra · Prominence Burn", fr: "Plus Ultra · Prominence Burn" }, fx: "pillar", c1: "255, 110, 30", c2: "60, 10, 0", kanji: "炎", lightning: true },
      "tomura-shigaraki": { arc: 7, name: { en: "Decay", fr: "Désintégration" }, fx: "domain", c1: "170, 170, 200", c2: "10, 10, 20", kanji: "崩壊" },
      "all-for-one": { arc: 8, name: { en: "Prime All For One", fr: "All For One à son apogée" }, fx: "domain", c1: "200, 30, 60", c2: "4, 0, 4", kanji: "魔王", lightning: true },
      "star-and-stripe": { arc: 8, name: { en: "New Order", fr: "New Order" }, fx: "aura", c1: "255, 240, 140", c2: "30, 60, 200", kanji: "新秩序", lightning: true },
    },
    haikyuu: {
      "yu-nishinoya": { arc: 1, name: { en: "Rolling Thunder", fr: "Rolling Thunder" }, fx: "aura", c1: "255, 200, 60", c2: "255, 120, 30", kanji: "守護神", lightning: true },
      "shoyo-hinata": { arc: 0, name: { en: "Freak quick", fr: "Attaque rapide de malade" }, fx: "aura", c1: "255, 140, 30", c2: "255, 230, 120", kanji: "飛べ" },
      "tobio-kageyama": { arc: 0, name: { en: "King of the Court", fr: "Le Roi du terrain" }, fx: "aura", c1: "90, 160, 255", c2: "10, 20, 50", kanji: "王様", lightning: true },
      "toru-oikawa": { arc: 1, name: { en: "Killer jump serve", fr: "Service smashé dévastateur" }, fx: "aura", c1: "120, 230, 210", c2: "10, 40, 40", kanji: "大王様" },
      "kotaro-bokuto": { arc: 2, name: { en: "Ace cross-shot", fr: "Smash croisé de l'as" }, fx: "aura", c1: "255, 210, 80", c2: "40, 30, 10", kanji: "エース", lightning: true },
      "wakatoshi-ushijima": { arc: 3, name: { en: "Left-handed cannon", fr: "Le canon gaucher" }, fx: "pillar", c1: "200, 120, 255", c2: "30, 6, 40", kanji: "怪童" },
      "atsumu-miya": { arc: 4, name: { en: "Twin minus tempo", fr: "Attaque rapide des jumeaux" }, fx: "aura", c1: "255, 190, 70", c2: "40, 10, 10", kanji: "双子", lightning: true },
      "kiyoomi-sakusa": { arc: 4, name: { en: "Spin spike", fr: "Smash à effet" }, fx: "aura", c1: "255, 230, 90", c2: "40, 40, 10", kanji: "スピン" },
    },
    fireforce: {
      joker: { arc: 2, name: { en: "The Joker's trick", fr: "Le tour du Joker" }, fx: "domain", c1: "200, 80, 255", c2: "255, 60, 120", kanji: "道化" },
      "arthur-boyle": { arc: 3, name: { en: "Knight King · Excalibur", fr: "Roi chevalier · Excalibur" }, fx: "pillar", c1: "120, 200, 255", c2: "255, 230, 120", kanji: "騎士王", lightning: true },
      "shinra-kusakabe": { arc: 0, name: { en: "Devil's Footprints", fr: "Empreintes du diable" }, fx: "aura", c1: "255, 120, 40", c2: "40, 6, 0", kanji: "悪魔", lightning: true },
      "benimaru-shinmon": { arc: 1, name: { en: "Shinmon style · Crimson Moon", fr: "Style Shinmon · Lune pourpre" }, fx: "pillar", c1: "255, 70, 80", c2: "30, 0, 10", kanji: "紅", lightning: true },
      "sho-kusakabe": { arc: 1, name: { en: "Adolla Link · Stopped time", fr: "Lien Adolla · Le temps arrêté" }, fx: "domain", c1: "220, 220, 255", c2: "6, 6, 20", kanji: "天照" },
      dragon: { arc: 3, name: { en: "Dragon transformation", fr: "Transformation en dragon" }, fx: "pillar", c1: "255, 90, 40", c2: "20, 4, 0", kanji: "竜", lightning: true },
    },
    slime: {
      benimaru: { arc: 2, name: { en: "Hell Flare", fr: "Hell Flare" }, fx: "domain", c1: "120, 90, 255", c2: "255, 60, 40", kanji: "黒炎獄" },
      "rimuru-tempest": { arc: 2, name: { en: "Megiddo", fr: "Megiddo" }, fx: "domain", c1: "120, 210, 255", c2: "4, 14, 40", kanji: "魔王", lightning: true },
      "veldora-tempest": { arc: 0, name: { en: "Storm Dragon", fr: "Dragon de la tempête" }, fx: "pillar", c1: "255, 220, 90", c2: "20, 30, 10", kanji: "暴風竜", lightning: true },
      diablo: { arc: 2, name: { en: "Primordial of Black", fr: "Le Primordial noir" }, fx: "domain", c1: "120, 60, 200", c2: "2, 0, 6", kanji: "悪魔" },
      "milim-nava": { arc: 3, name: { en: "Dragonoid · Drago Nova", fr: "Dragonoïde · Drago Nova" }, fx: "pillar", c1: "255, 110, 200", c2: "30, 4, 30", kanji: "破壊の暴君", lightning: true },
      "guy-crimson": { arc: 3, name: { en: "Primordial of Red", fr: "Le Primordial rouge" }, fx: "domain", c1: "230, 30, 50", c2: "10, 0, 2", kanji: "暗黒皇帝", lightning: true },
      "luminous-valentine": { arc: 3, name: { en: "Queen of the Night", fr: "Reine de la nuit" }, fx: "domain", c1: "200, 190, 255", c2: "10, 6, 20", kanji: "夜魔の女王" },
    },
    onepunchman: {
      orochi: { arc: 3, name: { en: "Monster King", fr: "Roi des monstres" }, fx: "domain", c1: "150, 60, 200", c2: "20, 0, 30", kanji: "怪人王" },
      bang: { arc: 2, name: { en: "Water Stream Rock Smashing Fist", fr: "Poing de l'eau qui brise la roche" }, fx: "aura", c1: "120, 220, 255", c2: "230, 250, 255", kanji: "流水岩砕拳" },
      genos: { arc: 0, name: { en: "Incineration Cannon", fr: "Canon incinérateur" }, fx: "pillar", c1: "255, 150, 40", c2: "255, 230, 160", kanji: "焼却" },
      saitama: { arc: 1, name: { en: "Serious Punch", fr: "Coup de poing sérieux" }, fx: "pillar", c1: "255, 230, 120", c2: "40, 30, 0", kanji: "マジ殴り", lightning: true },
      tatsumaki: { arc: 1, name: { en: "Tornado of Terror", fr: "La Tornade de la terreur" }, fx: "domain", c1: "90, 255, 150", c2: "4, 30, 10", kanji: "戦慄のタツマキ" },
      garou: { arc: 3, name: { en: "Hero Hunter", fr: "Le Chasseur de héros" }, fx: "aura", c1: "255, 255, 255", c2: "20, 20, 30", kanji: "怪人", lightning: true },
      boros: { arc: 1, name: { en: "Meteoric Burst", fr: "Explosion météorique" }, fx: "aura", c1: "120, 220, 255", c2: "20, 0, 40", kanji: "ボロス", lightning: true },
    },
  };

  // Forms with an anime clip (crew/assets/clips/<game>-<id>.mp4), played in the transformation cinematic. Bleach uses
  // the cut-scenes of Rebirth of Souls (2025), its most recent animation.
  const CLIPS = {
    demonslayer: ["yoriichi-tsugikuni", "kokushibo", "gyomei-himejima", "muzan-kibutsuji", "doma", "tanjiro-kamado", "kyojuro-rengoku", "akaza", "zenitsu-agatsuma"],
    myheroacademia: ["izuku-midoriya", "all-might", "endeavor", "all-for-one", "star-and-stripe", "tomura-shigaraki", "shoto-todoroki", "dabi", "katsuki-bakugo"],
    slime: ["rimuru-tempest", "diablo", "milim-nava", "guy-crimson", "luminous-valentine", "benimaru"],
    haikyuu: ["tobio-kageyama", "toru-oikawa", "kotaro-bokuto", "wakatoshi-ushijima", "atsumu-miya", "shoyo-hinata", "yu-nishinoya"],
    fireforce: ["shinra-kusakabe", "benimaru-shinmon", "dragon", "sho-kusakabe", "arthur-boyle", "joker"],
    onepunchman: ["saitama", "tatsumaki", "garou", "boros", "genos", "bang", "orochi"],
    onepiece: ["monkey-d-luffy", "gol-d-roger"],
    bleach: ["kaname-tosen", "tier-harribel", "nelliel-tu-odelschwanck", "coyote-starrk", "genryusai-yamamoto", "grimmjow-jaegerjaquez", "ichigo-kurosaki", "sosuke-aizen", "renji-abarai", "rukia-kuchiki", "uryu-ishida", "byakuya-kuchiki", "toshiro-hitsugaya", "ulquiorra-cifer", "sajin-komamura", "mayuri-kurotsuchi", "kenpachi-zaraki", "yhwach"],
    jujutsukaisen: ["ryomen-sukuna", "mahito", "jogo", "aoi-todo", "toji-fushiguro"],
    hunterxhunter: ["gon-freecss", "killua-zoldyck"],
    attackontitan: ["annie-leonhart", "reiner-braun", "bertholdt-hoover", "ymir", "zeke-yeager", "lara-tybur", "dina-fritz", "levi"],
  };
  for (const [game, ids] of Object.entries(CLIPS)) for (const id of ids) if (window.CREW_FORMS[game]?.[id]) window.CREW_FORMS[game][id].clip = true;
})();
