# Cut-out transformation portraits for the cinematic (crew/cinema.js): the character without its background,
# made with rembg's anime model (pip install rembg). A picture where the character fills the frame (a close-up)
# can't be cut cleanly: it is skipped and the cinematic shows it framed instead.
# Writes crew/assets/forms/cut/<game>-<id>.webp and crew/cutouts.js (the list of the ones that worked).
# Usage: python crew/scripts/cutouts.py [name …]   (names like "bleach-ichigo-kurosaki"; default: every form)
import glob
import json
import os
import sys

import numpy as np
from scipy import ndimage
from PIL import Image
from rembg import new_session, remove

HERE = os.path.dirname(os.path.abspath(__file__))
FORMS = os.path.join(HERE, "..", "assets", "forms")
OUT = os.path.join(FORMS, "cut")
LIST = os.path.join(HERE, "..", "cutouts.js")
os.makedirs(OUT, exist_ok=True)

names = sys.argv[1:] or sorted(os.path.splitext(os.path.basename(p))[0] for p in glob.glob(os.path.join(FORMS, "*.webp")))
try:
    with open(LIST, encoding="utf-8") as f:
        kept = set(json.loads(f.read().split("=", 1)[1].strip().rstrip(";")))
except (OSError, ValueError, IndexError):
    kept = set()

# Cut but not cleanly (manga pages, effects mistaken for the character): kept framed.
SKIP = {"bleach-as-nodt", "bleach-bambietta-basterbine", "bleach-liltotto-lamperd", "dragonball-beerus", "dragonball-zeno", "hunterxhunter-zeno-zoldyck", "blackclover-lucifero", "blackclover-megicula", "bleach-byakuya-kuchiki", "bleach-coyote-starrk", "bleach-ulquiorra-cifer", "onepiece-kaidou", "attackontitan-armin-arlert"}
session = new_session("isnet-anime")
for name in names:
    img = Image.open(os.path.join(FORMS, name + ".webp")).convert("RGB")
    cut = remove(img, session=session, post_process_mask=True)
    # Only the character: bits of background left apart from the main body are dropped.
    alpha = np.asarray(cut.split()[-1]).copy()
    labels, n = ndimage.label(alpha > 40)
    if n > 1:
        sizes = ndimage.sum(np.ones_like(alpha), labels, range(1, n + 1))
        keep = {i + 1 for i, v in enumerate(sizes) if v >= sizes.max() * 0.06}
        alpha[~np.isin(labels, list(keep))] = 0
        cut.putalpha(Image.fromarray(alpha))
    a = alpha > 128
    cover = a.mean()
    # How much of the top, left and right edges the character touches (the bottom may be cut off).
    edges = np.concatenate([a[0, :], a[:, 0], a[:, -1]]).mean()
    ok = 0.06 < cover < 0.62 and edges < 0.22 and name not in SKIP
    if ok:
        box = cut.getbbox()
        cut = cut.crop(box)
        cut.thumbnail((720, 900), Image.LANCZOS)
        cut.save(os.path.join(OUT, name + ".webp"), "WEBP", quality=88, method=6)
        kept.add(name)
    else:
        kept.discard(name)
        try:
            os.remove(os.path.join(OUT, name + ".webp"))
        except OSError:
            pass
    print(f"{'+' if ok else '-'} {name:44} cover {cover:.2f} edges {edges:.2f}")

with open(LIST, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by crew/scripts/cutouts.py: transformations with a clean cut-out portrait (assets/forms/cut/).\n")
    f.write("window.CREW_CUTOUTS = " + json.dumps(sorted(kept)) + ";\n")
print(len(kept), "cut-outs")
