// Downloads the transformation portraits used by Crew Roll (crew/forms.js) from the Fandom wikis.
// Usage: node crew/scripts/forms.mjs
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "assets", "forms");
// [wiki, game id, character id, wiki file]
const FILES = [
  ["dragonball", "dragonball", "goku", "File:Super Saiyan Goku (Kai).png"],
  ["dragonball", "dragonball", "vegeta", "File:Vegeta Super Saiyan Form.JPG"],
  ["dragonball", "dragonball", "gohan", "File:Gohan-super-saiyan-2.jpg"],
  ["dragonball", "dragonball", "future-trunks", "File:Future-trunks-super-saiyan-2-i5.png"],
  ["dragonball", "dragonball", "frieza", "File:Golden Frieza full.png"],
  ["dragonball", "dragonball", "goku-black", "File:Super Saiyan Rose Goku Black.png"],
  ["bleach", "bleach", "ichigo-kurosaki", "File:163Ichigo's Bankai, Tensa Zangetsu.png"],
  ["bleach", "bleach", "byakuya-kuchiki", "File:Byakuya & Reigai-Byakuya After Exchanging Attacks With Bankai.png"],
  ["bleach", "bleach", "renji-abarai", "File:223Renji's Bankai, Hihio Zabimaru.png"],
  ["bleach", "bleach", "toshiro-hitsugaya", "File:170Hitsugaya's Bankai, Daiguren Hyorinmaru.png"],
  ["bleach", "bleach", "ulquiorra-cifer", "File:RoS Ulquiorra Segunda Etapa.png"],
  ["bleach", "bleach", "grimmjow-jaegerjaquez", "File:BBSArena Grimmjow.png"],
  ["naruto", "naruto", "naruto-uzumaki", "File:Naruto's Sage Mode.png"],
  ["naruto", "naruto", "sasuke-uchiha", "File:Sasuke's Fully body Susanoo.png"],
  ["naruto", "naruto", "itachi-uchiha", "File:Itachi Armoured Susanoo NXB.png"],
  ["naruto", "naruto", "kakashi-hatake", "File:Kakashi's Mangekyō Sharingan.png"],
  ["naruto", "naruto", "might-guy", "File:Guy's Eight Inner Gates.png"],
  ["naruto", "naruto", "rock-lee", "File:Eight Gates-Rock Lee.png"],
  ["onepiece", "onepiece", "monkey-d-luffy", "File:Luffy Activates Gear 5.png"],
  ["onepiece", "onepiece", "roronoa-zoro", "File:Zoro Defeating Kaku with Asura.png"],
  ["jujutsu-kaisen", "jujutsukaisen", "satoru-gojo", "File:Satoru Gojo targets weakened Hanami (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "ryomen-sukuna", "File:Malevolent Shrine (SpecialZ).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "yuta-okkotsu", "File:Rika's presence behind Yuta (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "mahito", "File:Self-Embodiment of Perfection (SpecialZ).png"],
  ["hunterxhunter", "hunterxhunter", "killua-zoldyck", "File:129 - Godspeed Killua.png"],
  ["hunterxhunter", "hunterxhunter", "gon-freecss", "File:Adult Gon Anime.png"],
  ["hunterxhunter", "hunterxhunter", "kurapika", "File:Kurapika emperor time HXH 99 EP69.png"],
  ["attackontitan", "attackontitan", "eren-yeager", "File:Attack Titan character image (Eren Yeager).png"],
  ["attackontitan", "attackontitan", "annie-leonhart", "File:Female Titan character image (Annie Leonhart).png"],
  ["attackontitan", "attackontitan", "reiner-braun", "File:Armored Titan character image (Reiner Braun).png"],
  ["attackontitan", "attackontitan", "bertholdt-hoover", "File:Colossal Titan (Anime) character image (Bertholdt Hoover).png"],
  ["attackontitan", "attackontitan", "ymir", "File:Jaw Titan (Anime) character image (Ymir).png"],
  ["attackontitan", "attackontitan", "armin-arlert", "File:Colossal Titan (Anime) character image (Armin Arlelt).png"],
  ["attackontitan", "attackontitan", "zeke-yeager", "File:Beast Titan character image (Zeke Yeager).png"],
  ["attackontitan", "attackontitan", "porco-galliard", "File:Jaw Titan (Anime) character image (Porco Galliard).png"],
  ["attackontitan", "attackontitan", "pieck-finger", "File:Cart Titan character image (Pieck Finger).png"],
  ["attackontitan", "attackontitan", "lara-tybur", "File:War Hammer Titan character image (Lara Tybur).png"],
  ["attackontitan", "attackontitan", "falco-grice", "File:Jaw Titan (Anime) character image (Falco Grice).png"],
  ["bleach", "bleach", "sosuke-aizen", "File:Ep295AizenFirstFusion.png"],
  ["bleach", "bleach", "kenpachi-zaraki", "File:Ep410KenpachiBankaiFace.png"],
  ["bleach", "bleach", "sajin-komamura", "File:248Kokujo Tengen Myo'o stands.png"],
  ["bleach", "bleach", "coyote-starrk", "File:BBSResurreccion Starrk.png"],
  ["bleach", "bleach", "mayuri-kurotsuchi", "File:303Mayuri's Bankai, Konjiki Ashisogi Jizo.png"],
  ["bleach", "bleach", "yhwach", "File:Ep396TheAlmighty.png"],
  ["dragonball", "dragonball", "cell", "File:Cell-Super-Perfect.png"],
  ["dragonball", "dragonball", "majin-buu", "File:Super Buu.PNG"],
  ["dragonball", "dragonball", "piccolo", "File:Orange Piccolo full.PNG"],
  ["dragonball", "dragonball", "jiren", "File:Super Full Power Jiren (manga).png"],
  ["dragonball", "dragonball", "zamasu", "File:Fusion-Zamasu.jpg"],
  ["dragonball", "dragonball", "kale", "File:Kale True Legendary Super Saiyan.png"],
  ["naruto", "naruto", "gaara", "File:Full Shukaku Gaara.png"],
  ["naruto", "naruto", "jiraiya", "File:Sage mode.png"],
  ["naruto", "naruto", "madara-uchiha", "File:Madara Jinchuriki anime.png"],
  ["naruto", "naruto", "obito-uchiha", "File:Obito Juubi Jinchuriki.png"],
  ["naruto", "naruto", "minato-namikaze", "File:Minato's nine-tails chakra mode.png"],
  ["naruto", "naruto", "kabuto-yakushi", "File:Kabuto's Sage Mode.png"],
  ["onepiece", "onepiece", "sanji", "File:Sanji's Raid Suit.png"],
  ["onepiece", "onepiece", "tony-tony-chopper", "File:Post Timeskip Monster Point.png"],
  ["onepiece", "onepiece", "polo-marco", "File:Marco Phoenix Thousand Storm.png"],
  ["onepiece", "onepiece", "kaidou", "File:Kaidou Dragon Color Scheme.png"],
  ["onepiece", "onepiece", "rob-lucci", "File:Neko Neko no Mi, Model Leopard Human-Beast Form.png"],
  ["onepiece", "onepiece", "magellan", "File:Venom Demon Jigoku no Shinpan.png"],
  ["onepiece", "onepiece", "sakazuki", "File:Magu Magu no Mi Infobox.png"],
  ["onepiece", "onepiece", "kuzan", "File:Hie Hie no Mi Infobox.png"],
  ["onepiece", "onepiece", "borsalino", "File:Pika Pika no Mi Infobox.png"],
  ["bleach", "bleach", "barragan-louisenbairn", "File:Ep276Baraggan's Resurrección, Arrogante.png"],
  ["onepiece", "onepiece", "imu", "File:Imu Further Transformation.png"],
  ["onepiece", "onepiece", "king", "File:Ryu Ryu no Mi, Model Pteranodon Beast Form.png"],
  ["onepiece", "onepiece", "charlotte-katakuri", "File:Katakuri's Flame Haki.png"],
  ["jujutsu-kaisen", "jujutsukaisen", "megumi-fushiguro", "File:Chimera Shadow Garden inside Horizon of the Captivating Skandha (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "jogo", "File:Coffin of the Iron Mountain (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "maki-zen-in", "File:Maki Zenin vs. Ogi Zenin (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "kinji-hakari", "File:Kinji Hakari's cursed energy (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "hiromi-higuruma", "File:Deadly Sentencing (Anime).png"],
  ["hunterxhunter", "hunterxhunter", "isaac-netero", "File:2011 EP122 ED Card Netero Guanyin Bodhisattva.png"],
  ["hunterxhunter", "hunterxhunter", "biscuit-krueger", "File:2011 EP73 Biscuit True Form full appearance.png"],
  ["hunterxhunter", "hunterxhunter", "neferpitou", "File:Terpsichora 2011.png"],
  ["hunterxhunter", "hunterxhunter", "menthuthuyoupi", "File:118 - Knuckle vs. Youpi 1.png"],
  ["blackclover", "blackclover", "asta", "File:Asta and Liebe in true Unite.png"],
  ["blackclover", "blackclover", "liebe", "File:Liebe anime profile.png"],
  ["blackclover", "blackclover", "zagred", "File:Zagred anime profile.png"],
  ["blackclover", "blackclover", "megicula", "File:Megicula manifests out of Vanica.png"],
  ["blackclover", "blackclover", "lucifero", "File:Lucifero partially manifests.png"],
  ["blackclover", "blackclover", "vanica-zogratis", "File:Vanica at 100%.png"],
  ["blackclover", "blackclover", "zenon-zogratis", "File:Zenon at 100%.png"],
  ["blackclover", "blackclover", "nacht-faust", "File:Nacht in Gallus × Felis × Canis Mode.png"],
  ["blackclover", "blackclover", "yuno", "File:Spirit Dive Yuno - BCM.png"],
  ["blackclover", "blackclover", "noelle-silva", "File:Valkyrie Dress.png"],
  ["blackclover", "blackclover", "fuegoleon-vermillion", "File:Fuegoleon emerges with Salamander.png"],
  ["blackclover", "blackclover", "dante-zogratis", "File:Dante at 100%.png"],
  ["attackontitan", "attackontitan", "rod-reiss", "File:Rod Reiss (Anime) character image (Titan).png"],
  ["attackontitan", "attackontitan", "dina-fritz", "File:Dina Fritz (Anime) character image (Titan).png"],
  ["attackontitan", "attackontitan", "ymir-fritz", "File:Founding Titan (Anime) character image (Ymir Fritz).png"],
  ["attackontitan", "attackontitan", "grisha-yeager", "File:Attack Titan (Anime) character image (Grisha Jaeger).png"],
  ["attackontitan", "attackontitan", "marcel-galliard", "File:Jaw Titan (Anime) character image (Marcel Galliard).png"],
  ["bleach", "bleach", "genryusai-yamamoto", "File:Ep371YamamotoConfrontsRoyd.png"],
  ["bleach", "bleach", "ichibe-hyosube", "File:Ep374IchibeiCharaPic.png"],
  ["hunterxhunter", "hunterxhunter", "zeno-zoldyck", "File:111 - Zeno.png"],
  ["hunterxhunter", "hunterxhunter", "chrollo-lucilfer", "File:HxH2011 EP41 Chrollo appears.png"],
  ["hunterxhunter", "hunterxhunter", "meruem", "File:128 - Meruem Wings.png"],
  ["hunterxhunter", "hunterxhunter", "ging-freecss", "File:Ging Freecss HCE Portrait.png"],
  ["hunterxhunter", "hunterxhunter", "alluka-zoldyck", "File:2011 EP146 Nanika loves Killua.png"],
  ["dragonball", "dragonball", "android-17", "File:Android 17 Tournament of Power.png"],
  ["dragonball", "dragonball", "beerus", "File:Hakai 1.jpg"],
  ["dragonball", "dragonball", "whis", "File:Whis (DBS ep67).png"],
  ["dragonball", "dragonball", "champa", "File:Champa yelling at Beerus (DBS Trailer 2).png"],
  ["dragonball", "dragonball", "vados", "File:Dragon-Ball-Super-107-Vados.jpg"],
  ["dragonball", "dragonball", "zeno", "File:Zeno and Future Zeno erase Universe 9.jpg"],
  ["dragonball", "dragonball", "grand-priest", "File:Daishinkan.png"],
  ["naruto", "naruto", "hashirama-senju", "File:Hashirama's Sage Mode.png"],
  ["naruto", "naruto", "kaguya-otsutsuki", "File:Kaguya's dojutsu.png"],
  ["naruto", "naruto", "hagoromo-otsutsuki", "File:Hagoromo Susanoo.png"],
  ["onepiece", "onepiece", "shanks", "File:Shanks Anime Infobox.png"],
  ["onepiece", "onepiece", "monkey-d-dragon", "File:Monkey D. Dragon Anime Infobox.png"],
  ["onepiece", "onepiece", "gol-d-roger", "File:Roger's Haki.png"],
  ["onepiece", "onepiece", "dracule-mihawk", "File:Dracule Mihawk Anime Infobox.png"],
  ["onepiece", "onepiece", "marshall-d-teach", "File:Blackbeard with Yami Yami no Mi and Gura Gura no Mi.png"],
  ["onepiece", "onepiece", "monkey-d-garp", "File:Garp Iron Ball.png"],
  ["onepiece", "onepiece", "silvers-rayleigh", "File:Rayleigh's Armament Haki.png"],
  ["onepiece", "onepiece", "edward-newgate", "File:Whitebeard Using Gura Gura no Mi Ability.png"],
  ["onepiece", "onepiece", "sengoku", "File:Hito Hito no Mi, Model Daibutsu Infobox.png"],
  ["onepiece", "onepiece", "issho", "File:Zushi Zushi no Mi Infobox.png"],
  ["onepiece", "onepiece", "charlotte-linlin", "File:Soru Soru no Mi Infobox.png"],
  ["onepiece", "onepiece", "kouzuki-oden", "File:Tougen Totsuka.png"],
  ["onepiece", "onepiece", "scopper-gaban", "File:Scopper Gaban 26 Years Ago.png"],
  ["onepiece", "onepiece", "figarland-garling", "File:Figarland Garling Anime Infobox.png"],
  ["jujutsu-kaisen", "jujutsukaisen", "aoi-todo", "File:Boogie Woogie (SpecialZ).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "toji-fushiguro", "File:Toji reveals the Inverted Spear of Heaven (Anime).png"],
  ["jujutsu-kaisen", "jujutsukaisen", "yuki-tsukumo", "File:Yuki Tsukumo comes to the rescue (Anime).png"],
  ["blackclover", "blackclover", "yami-sukehiro", "File:Yami slashes wildly.png"],
  ["blackclover", "blackclover", "mereoleona-vermillion", "File:Mereoleona for Spade raid.png"],
  ["blackclover", "blackclover", "julius-novachrono", "File:Julius anime profile.png"],
  ["blackclover", "blackclover", "licht", "File:Licht casts forbidden magic spell.png"],
  ["attackontitan", "attackontitan", "levi", "File:Levi slices up the Beast Titan.png"],
  ["dragonball", "dragonball", "vegito", "File:SSGSS Barrier Vegito.png"],
  ["dragonball", "dragonball", "gogeta", "File:SSBGogeta.png"],
  ["dragonball", "dragonball", "kefla", "File:Kefla SS2.jpeg"],
  ["dragonball", "dragonball", "broly", "File:Broly - The Legendary Super Saiyan - LSSJ Broly.jpg"],
  ["onepiece", "onepiece", "rocks-d-xebec", "File:Rocks D. Xebec Full Appearance.png"],
  ["onepiece", "onepiece", "aramaki", "File:Mori Mori no Mi Infobox.png"],
  ["bleach", "bleach", "tier-harribel", "File:Ep275Harribel's Resurreccion, Tiburon.png"],
  ["bleach", "bleach", "nelliel-tu-odelschwanck", "File:195Nelliel's Resurreccion, Gamuza.png"],
  ["bleach", "bleach", "askin-nakk-le-vaar", "File:Ep408GiftBallDeluxe.png"],
  ["bleach", "bleach", "bambietta-basterbine", "File:Ep383BambiettaVollstandig.png"],
  ["bleach", "bleach", "liltotto-lamperd", "File:Ep387LiltottoVollstandigGagael.png"],
  ["bleach", "bleach", "as-nodt", "File:Ep385AsVollstandigTatarforas.png"],
  ["bleach", "bleach", "lille-barro", "File:Ep403LilleVollstandigJillielSecondFormFull.png"],
  ["bleach", "bleach", "gremmy-thoumeaux", "File:Ep386GremmyCreatesHand.png"],
  ["bleach", "bleach", "jugram-haschwalth", "File:Ep409HaschwalthEvadesLaser.png"],
  ["bleach", "bleach", "bazz-b", "File:Ep404BurnerFinger3.png"],
  ["bleach", "bleach", "uryu-ishida", "File:125Quincy - Letzt Stil.png"],
  ["bleach", "bleach", "kirio-hikifune", "File:Ep375HikifuneExplainsPurpose.png"],
  ["bleach", "bleach", "kugo-ginjo", "File:Ep365GinjoBankai.png"],
  ["bleach", "bleach", "yoruichi-shihoin", "File:Ep56Shunkō3.png"],
  ["bleach", "bleach", "yoruichi-shihoin-2", "File:Shunkō- Raijin Senkei.png"],
  // Card picture (forms.js "card"): Vasto Lorde, cropped by hand from the 2261×1080 original (x 330–1490).
  ["bleach", "bleach", "ichigo-kurosaki-vl", "File:BBSFully Hollowfied Ichigo.png"],
  ["solo-leveling", "sololeveling", "beru", "File:Ant King Anime2.png"],
  ["solo-leveling", "sololeveling", "ashborn", "File:Ashborn22.jpg"],
  ["solo-leveling", "sololeveling", "antares", "File:Antares Dragon Form.png"],
  ["solo-leveling", "sololeveling", "sung-jinwoo", "File:Sung Jinwoo Monarch.jpg"],
  ["solo-leveling", "sololeveling", "sung-jinwoo-2", "File:Sun Jin-Woo panel Shadow Monarch.webp"],
  ["solo-leveling", "sololeveling", "baek-yoonho", "File:Baek Yoon-Ho transformation.png"],
  ["solo-leveling", "sololeveling", "sung-il-hwan", "File:Sung Il-Hwan.png"],
  // October 2026: a different picture from the portrait for every form (transformation or signature move), cropped
  // to a centred portrait by hand.
  ["bleach", "bleach", "genryusai-yamamoto", "File:BBSBeyond Bankai Yamamoto.png"],
  ["onepiece", "onepiece", "shanks", "File:Shanks Emperor Power Thousand Storm.png"],
  ["onepiece", "onepiece", "monkey-d-garp", "File:Fist of Love.png"],
  ["onepiece", "onepiece", "dracule-mihawk", "File:Mihawk One Piece Odyssey.png"],
  ["onepiece", "onepiece", "monkey-d-dragon", "File:Dragon Digitally Colored Manga.png"],
  ["onepiece", "onepiece", "figarland-garling", "File:Garling Hunting.png"],
  ["bleach", "bleach", "ichibe-hyosube", "File:Ep392IchibēShikaiIchimonji.png"],
  ["naruto", "naruto", "hagoromo-otsutsuki", "File:Naruto and Sasuke obtain Rikudo Power.png"],
  ["dragonball", "dragonball", "whis", "File:DBXV2 Whis (Partner Customization) Gift - Poo Staff (Special Costume).png"],
  ["hunterxhunter", "hunterxhunter", "ging-freecss", "File:Chap 347 - Ging's warping punch.png"],
  ["blackclover", "blackclover", "zagred", "File:Zagred profile.png"],
  ["blackclover", "blackclover", "julius-novachrono", "File:Julius discovers magic tool with Swallowtail.png"],
  ["blackclover", "blackclover", "lucius-zogratis", "File:Lucius on Judgment Day.png"],
  ["myheroacademia", "myheroacademia", "all-might", "File:All Might punches All For One.png"],
  ["myheroacademia", "myheroacademia", "all-for-one", "File:All For One (Rewind) Artwork (All's Justice).png"],
  ["myheroacademia", "myheroacademia", "izuku-midoriya", "File:Izuku Midoriya (Full Cowl 100%) Artwork (All's Justice).png"],
  ["myheroacademia", "myheroacademia", "tomura-shigaraki", "File:Tomura Shigaraki Artwork 3 Puzzle and Dragons.png"],
  ["myheroacademia", "myheroacademia", "star-and-stripe", "File:Star and Stripe uses New Order to remove the air.png"],
  ["myheroacademia", "myheroacademia", "mirio-togata", "File:Phantom Menace.png"],
  ["myheroacademia", "myheroacademia", "gigantomachia", "File:Gigantomachia (Single-Minded).png"],
  ["kimetsu-no-yaiba", "demonslayer", "gyomei-himejima", "File:Stone Breathing (Zenshuchuten).png"],
  ["kimetsu-no-yaiba", "demonslayer", "yoriichi-tsugikuni", "File:Sun Breathing - Thirteenth Form.png"],
  ["kimetsu-no-yaiba", "demonslayer", "muzan-kibutsuji", "File:Muzan colored body (combat form) 2.png"],
  ["kimetsu-no-yaiba", "demonslayer", "kokushibo", "File:Kokushibo (Anime).png"],
  ["kimetsu-no-yaiba", "demonslayer", "giyu-tomioka", "File:Water Breathing (Zenshuchuten).png"],
  ["kimetsu-no-yaiba", "demonslayer", "muichiro-tokito", "File:Muichiro uses Lunar Dispersing Mist against Gyokko's attack.png"],
  ["kimetsu-no-yaiba", "demonslayer", "sanemi-shinazugawa", "File:Wind Breathing (Zenshuchuten).png"],
  ["haikyuu", "haikyuu", "tobio-kageyama", "File:Kageyama-5star.png"],
  ["haikyuu", "haikyuu", "kotaro-bokuto", "File:Kōtarō Bokuto Illustration.jpg"],
  ["haikyuu", "haikyuu", "wakatoshi-ushijima", "File:Wakatoshi Ushijima The Volleyball Illustration.png"],
  ["haikyuu", "haikyuu", "atsumu-miya", "File:Atsumu Miya Illustration.jpg"],
  ["haikyuu", "haikyuu", "kiyoomi-sakusa", "File:Kiyoomi Sakusa The Volleyball Illustration.png"],
  ["haikyuu", "haikyuu", "tetsuro-kuroo", "File:Tetsurō Kuroo Illustration.png"],
  ["haikyuu", "haikyuu", "morisuke-yaku", "File:Morisuke Yaku The Volleyball Illustration.png"],
  ["haikyuu", "haikyuu", "satori-tendo", "File:Tendo s3-e8-2.png"],
  ["haikyuu", "haikyuu", "osamu-miya", "File:Osamu Miya Illustration.jpg"],
  ["haikyuu", "haikyuu", "aran-ojiro", "File:Aran s4-e25-1.png"],
  ["haikyuu", "haikyuu", "korai-hoshiumi", "File:Kōrai Hoshiumi Illustration.jpg"],
  ["fireforce", "fireforce", "benimaru-shinmon", "File:Benimaru vs Infernal.png"],
  ["fireforce", "fireforce", "sho-kusakabe", "File:Shinra & Shō.png"],
  ["fireforce", "fireforce", "dragon", "File:Dragon's Persona.png"],
  ["fireforce", "fireforce", "leonard-burns", "File:Shinra Kicks Leonard.png"],
  ["tensura", "slime", "rimuru-tempest", "File:That Time I Got Reincarnated as a Slime - Episode 56 (S3E08) -English Sub-"],
  ["tensura", "slime", "veldora-tempest", "File:Veldora Tempest -The Storm Dragon-.png"],
  ["tensura", "slime", "diablo", "File:Episode 70 - Diablo.jpg"],
  ["tensura", "slime", "testarossa", "File:Isekai Memories - Testarossa, Bewitching White Demon.png"],
  ["tensura", "slime", "ultima", "File:Isekai Memories - Ultima, Venomous Violet Demon.png"],
  ["tensura", "slime", "carrera", "File:Isekai Memories - Carrera, Condemning Yellow Demon.png"],
  ["tensura", "slime", "leon-cromwell", "File:Leon Cromwell -The Platinum Devil-.png"],
  ["tensura", "slime", "hinata-sakaguchi", "File:Episode 74 - Disintegration.jpg"],
  ["tensura", "slime", "chloe-aubert", "File:Isekai Memories - Chloe Aubert, Everlasting Elegance.png"],
  ["tensura", "slime", "velzard", "File:Velzard -The White Ice Dragon-.png"],
  ["onepunchman", "onepunchman", "saitama", "File:Ova saitama serious heroism.png"],
  ["onepunchman", "onepunchman", "tatsumaki", "File:Caught up in Tatsumaki's power anime.png"],
  ["onepunchman", "onepunchman", "watchdog-man", "File:Watchdog Man (A Hero Nobody Knows).png"],
  ["onepunchman", "onepunchman", "psykos", "File:Orochi Post-Psykos-Fusion.png"],
  ["onepunchman", "onepunchman", "bomb", "File:Whirlwind Iron Cutting Fist.png"],
  ["solo-leveling", "sololeveling", "thomas-andre", "File:Anime Episode 21 Thomas Andre.jpg"],
  ["solo-leveling", "sololeveling", "liu-zhigang", "File:Zhigang8.jpg"],
  ["solo-leveling", "sololeveling", "igris", "File:Solo leveling arise igris character profile2.jpg"],
  ["solo-leveling", "sololeveling", "bellion", "File:Bellion Vs Beru.jpeg"],
  ["solo-leveling", "sololeveling", "yogumunt", "File:Yogumunt.jpeg"],
];
// Small copies for avatars and lists: crew/assets/forms/sm/ (240 px wide), made from every form picture.
// Pictures supplied by hand (not on the wiki): Rukia's and Tosen's forms, Ichigo's and Byakuya's later looks
// (bleach-ichigo-kurosaki-2, bleach-byakuya-kuchiki-2).
// node crew/scripts/forms.mjs <game/id> … downloads only those.
const only = process.argv.slice(2);
// The image CDN only serves files requested from the wiki itself.
const headers = (wiki) => ({ "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36", Referer: `https://${wiki}.fandom.com/` });

await mkdir(OUT, { recursive: true });
const paths = {};
for (const [wiki, game, id, file] of FILES) {
  if (only.length && !only.includes(`${game}/${id}`)) continue;
  try {
    const url = `https://${wiki}.fandom.com/api.php?` + new URLSearchParams({ action: "query", titles: file, prop: "imageinfo", iiprop: "url", iiurlwidth: "640", format: "json" });
    const info = await (await fetch(url, { headers: headers(wiki) })).json();
    const src = Object.values(info.query.pages)[0]?.imageinfo?.[0]?.thumburl;
    if (!src) throw new Error("no image");
    const buf = Buffer.from(await (await fetch(src, { headers: headers(wiki) })).arrayBuffer());
    const ext = buf.subarray(8, 12).toString() === "WEBP" ? "webp" : buf[0] === 0xff ? "jpg" : "png";
    const name = `${game}-${id}.${ext}`;
    await writeFile(join(OUT, name), buf);
    paths[`${game}/${id}`] = `assets/forms/${name}`;
    console.log(`✓ ${game}/${id} ${(buf.length / 1024).toFixed(0)} KB`);
  } catch (e) {
    console.log(`✗ ${game}/${id}: ${e.message}`);
  }
}
console.log(JSON.stringify(paths, null, 1));
