// Source list for Narutodle. Gender, age, rank, clan, village, chakra natures, portrait and first arc are
// scraped from the Naruto wiki (scrape.mjs). Values set here override what is scraped.
//
// Arc indexes (anime):
//   0 Land of Waves (Naruto 1–19) · 1 Chūnin Exams (20–67) · 2 Konoha Crush & Tsunade (68–100)
//   3 Sasuke Recovery (107–135) · 4 Kazekage Rescue (Shippūden 1–32) · 5 Tenchi Bridge & Akatsuki (33–88)
//   6 Itachi Pursuit & Pain (113–175) · 7 Five Kage Summit (197–214) · 8 Fourth Shinobi World War (215–479)
//
// Any field may be { arcIndex: value } to stay spoiler-free (same rule as the other categories).

const K = ["Konohagakure"];
const AK = ["Akatsuki"];

export const seed = [
  // Land of Waves
  { wiki: "Naruto Uzumaki", nature: { 0: ["Unknown"], 5: ["Wind"], 8: ["Wind", "Fire", "Lightning", "Earth", "Water"] } },
  { wiki: "Sasuke Uchiha", nature: { 0: ["Fire"], 2: ["Fire", "Lightning"] }, village: { 0: K, 3: ["Otogakure"], 7: AK, 8: K } },
  { wiki: "Sakura Haruno", clan: ["None"] },
  { wiki: "Kakashi Hatake" },
  { wiki: "Iruka Umino" },
  { wiki: "Hiruzen Sarutobi" },
  { wiki: "Konohamaru Sarutobi" },
  { wiki: "Mizuki", village: K },
  { wiki: "Zabuza Momochi", village: ["Kirigakure"] },
  { wiki: "Haku", village: ["Kirigakure"] },
  { wiki: "Tazuna" },
  { wiki: "Inari" },
  { wiki: "Gatō" },
  { wiki: "Minato Namikaze" },
  // Chūnin Exams
  { wiki: "Rock Lee" },
  { wiki: "Neji Hyūga" },
  { wiki: "Tenten" },
  { wiki: "Might Guy" },
  { wiki: "Hinata Hyūga" },
  { wiki: "Kiba Inuzuka" },
  { wiki: "Shino Aburame" },
  { wiki: "Kurenai Yūhi" },
  { wiki: "Shikamaru Nara" },
  { wiki: "Chōji Akimichi" },
  { wiki: "Ino Yamanaka" },
  { wiki: "Asuma Sarutobi" },
  { wiki: "Gaara" },
  { wiki: "Kankurō" },
  { wiki: "Temari", clan: ["Kazekage"], village: ["Sunagakure"] },
  { wiki: "Kabuto Yakushi", village: { 1: ["Konohagakure", "Otogakure"] } },
  { wiki: "Orochimaru", gender: "M" },
  { wiki: "Anko Mitarashi" },
  { wiki: "Ibiki Morino" },
  { wiki: "Hayate Gekkō" },
  { wiki: "Dosu Kinuta" },
  { wiki: "Zaku Abumi" },
  { wiki: "Kin Tsuchi" },
  { wiki: "Baki" },
  { wiki: "Hiashi Hyūga" },
  { wiki: "Hanabi Hyūga" },
  { wiki: "Shikaku Nara" },
  { wiki: "Inoichi Yamanaka" },
  { wiki: "Chōza Akimichi" },
  // Konoha Crush & Tsunade
  { wiki: "Itachi Uchiha", village: AK },
  { wiki: "Kisame Hoshigaki", village: AK },
  { wiki: "Jiraiya" },
  { wiki: "Tsunade" },
  { wiki: "Shizune" },
  { wiki: "Kimimaro" },
  { wiki: "Tayuya" },
  { wiki: "Sakon and Ukon", name: "Sakon" },
  { wiki: "Jirōbō" },
  { wiki: "Kidōmaru" },
  { wiki: "Gamabunta" },
  // Shippūden
  { wiki: "Sai", clan: ["None"] },
  { wiki: "Yamato" },
  { wiki: "Deidara", village: AK },
  { wiki: "Sasori", village: AK },
  { wiki: "Chiyo" },
  { wiki: "Hidan", village: AK },
  { wiki: "Kakuzu", village: AK },
  { wiki: "Nagato", village: AK },
  { wiki: "Konan", village: AK },
  { wiki: "Obito Uchiha", nature: { 0: ["Fire"], 8: ["Fire", "Wood", "Yin", "Yang"] }, village: { 0: K, 8: ["Konohagakure", "Akatsuki"] } },
  { wiki: "Suigetsu Hōzuki", village: { 6: ["Kirigakure", "Otogakure"], 7: ["Kirigakure", "Otogakure", "Akatsuki"] } },
  { wiki: "Karin", village: { 6: ["Otogakure", "Kusagakure"], 7: ["Otogakure", "Kusagakure", "Akatsuki"] } },
  { wiki: "Jūgo", clan: ["None"], village: { 6: ["Otogakure"], 7: ["Otogakure", "Akatsuki"] } },
  { wiki: "Killer B" },
  { wiki: "A (Fourth Raikage)", name: "A (Fourth Raikage)" },
  { wiki: "Ōnoki" },
  { wiki: "Mei Terumī" },
  { wiki: "Darui" },
  { wiki: "Ao" },
  { wiki: "Kurotsuchi" },
  { wiki: "Danzō Shimura", nature: { 4: ["Wind"], 7: ["Wind", "Wood", "Earth", "Water", "Fire"] } },
  { wiki: "Fukasaku" },
  { wiki: "Yugito Nii" },
  { wiki: "Madara Uchiha" },
  { wiki: "Hashirama Senju" },
  { wiki: "Tobirama Senju" },
  { wiki: "Kushina Uzumaki" },
  { wiki: "Kaguya Ōtsutsuki" },
  { wiki: "Shisui Uchiha" },
  { wiki: "Rin Nohara" },
  { wiki: "Utakata" },
  { wiki: "Yagura Karatachi" },
  { wiki: "Hagoromo Ōtsutsuki" },
  { wiki: "Kinkaku" },
  { wiki: "Ginkaku" },
  { wiki: "Chōjūrō" },
  { wiki: "Omoi" },
  { wiki: "Karui", clan: ["None"], village: ["Kumogakure"] },
  { wiki: "Samui" },
];
