// Scrapes character portraits + heights from the Bleach fandom wiki and writes data/characters.js.
// Usage: node scripts/scrape.mjs
import { mkdir, writeFile, access } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { seed } from "./seed.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const API = "https://bleach.fandom.com/api.php";
const IMG_DIR = join(ROOT, "assets", "characters");
const UA = { "User-Agent": "Bleachdle fan game scraper (personal project)" };
// The image CDN only serves files when they are requested from the wiki itself.
const IMG_HEADERS = { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36", Referer: "https://bleach.fandom.com/" };

const slug = (s) =>
  s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function api(params) {
  const url = `${API}?${new URLSearchParams({ format: "json", redirects: "1", ...params })}`;
  const res = await fetch(url, { headers: UA });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

async function resolveTitle(title) {
  const q = await api({ action: "query", titles: title });
  const page = Object.values(q.query.pages)[0];
  if (!("missing" in page)) return page.title;
  const s = await api({ action: "query", list: "search", srsearch: title, srlimit: "1" });
  return s.query.search[0]?.title ?? null;
}

async function pageImage(title) {
  const q = await api({ action: "query", titles: title, prop: "pageimages", pithumbsize: "320" });
  return Object.values(q.query.pages)[0]?.thumbnail?.source ?? null;
}

async function infoboxHeight(title) {
  const p = await api({ action: "parse", page: title, prop: "wikitext", section: "0" });
  const text = p.parse?.wikitext?.["*"] ?? "";
  // The page also has a tab template with its own "height" field, so keep the one in centimetres.
  const field = [...text.matchAll(/\|\s*height\s*=([\s\S]*?)(?=\n\s*\||\n\}\})/gi)].map((m) => m[1]).find((v) => /cm/i.test(v));
  if (!field) return null;
  const clean = field.replace(/<ref[\s\S]*?(<\/ref>|\/>)/gi, "");
  const parts = clean.split(/<br\s*\/?>/i).filter((s) => !/formerly|previously|pre-|child|young/i.test(s));
  for (const part of parts) {
    const cm = part.match(/(\d{2,4}(?:\.\d+)?)\s*cm/i);
    if (cm) return Math.round(parseFloat(cm[1]));
  }
  return null;
}

// The wiki CDN serves WebP whatever the file name says, so the extension comes from the bytes.
async function download(url, id) {
  const res = await fetch(url, { headers: IMG_HEADERS });
  if (!res.ok) throw new Error(`image ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const ext = buf.subarray(8, 12).toString() === "WEBP" ? "webp" : buf[0] === 0xff ? "jpg" : "png";
  await writeFile(join(IMG_DIR, `${id}.${ext}`), buf);
  return `assets/characters/${id}.${ext}`;
}

await mkdir(IMG_DIR, { recursive: true });
const out = [];
for (const c of seed) {
  const id = slug(c.name);
  const entry = { id, ...c };
  delete entry.wiki;
  try {
    const title = await resolveTitle(c.wiki);
    if (!title) throw new Error("page not found");
    const [img, h] = await Promise.all([pageImage(title), infoboxHeight(title)]);
    if (h && h > 40 && h < 2000) entry.height = h;
    entry.image = img ? await download(img, id) : null;
    console.log(`✓ ${c.name.padEnd(28)} ${title.padEnd(32)} ${String(entry.height).padStart(4)}cm ${img ? "img" : "NO IMG"}`);
  } catch (e) {
    entry.image = null;
    console.log(`✗ ${c.name}: ${e.message}`);
  }
  out.push(entry);
}

const js = `// Generated by scripts/scrape.mjs — do not edit by hand, edit scripts/seed.mjs instead.\nwindow.DLE_CHARACTERS = ${JSON.stringify(out, null, 1)};\n`;
await mkdir(join(ROOT, "data"), { recursive: true });
await writeFile(join(ROOT, "data", "characters.js"), js);
console.log(`\n${out.length} characters written to data/characters.js`);
