// Source list for Jujutsudle. Race, gender, age, hair, affiliation, grade, portrait and first arc are
// scraped from the Jujutsu Kaisen wiki (scrape.mjs). Values set here override what is scraped.
//
// Arc indexes (anime episodes):
//   0 Fearsome Womb (1–5) · 1 Vs. Mahito (6–13) · 2 Kyoto Goodwill Event (14–21) · 3 Death Painting (22–24)
//   4 Hidden Inventory (25–29) · 5 Shibuya Incident (30–47) · 6 Culling Game (48–)
//
// Any field may be { arcIndex: value } to stay spoiler-free.

export const seed = [
  { wiki: "Yuji Itadori", grade: "None" },
  { wiki: "Megumi Fushiguro" },
  { wiki: "Nobara Kugisaki" },
  { wiki: "Satoru Gojo" },
  { wiki: "Sukuna", name: "Ryomen Sukuna" },
  { wiki: "Kento Nanami" },
  { wiki: "Maki Zenin", name: "Maki Zen'in" },
  { wiki: "Toge Inumaki" },
  { wiki: "Panda" },
  { wiki: "Yuta Okkotsu", aff: ["Tokyo Jujutsu High"] },
  { wiki: "Masamichi Yaga" },
  { wiki: "Shoko Ieiri" },
  { wiki: "Kiyotaka Ijichi" },
  { wiki: "Aoi Todo" },
  { wiki: "Mai Zenin", name: "Mai Zen'in" },
  { wiki: "Kasumi Miwa" },
  { wiki: "Noritoshi Kamo" },
  { wiki: "Momo Nishimiya" },
  { wiki: "Kokichi Muta", name: "Mechamaru", aff: { 2: ["Kyoto Jujutsu High"], 5: ["Kyoto Jujutsu High", "Curse Users"] } },
  { wiki: "Utahime Iori" },
  { wiki: "Yoshinobu Gakuganji" },
  { wiki: "Mahito" },
  { wiki: "Jogo", hair: ["None"] },
  { wiki: "Hanami", hair: ["None"] },
  { wiki: "Dagon", hair: ["None"] },
  { wiki: "Junpei Yoshino" },
  { wiki: "Suguru Geto" },
  { wiki: "Choso" },
  { wiki: "Eso" },
  { wiki: "Kechizu" },
  { wiki: "Mei Mei" },
  { wiki: "Ui Ui" },
  { wiki: "Atsuya Kusakabe" },
  { wiki: "Toji Fushiguro" },
  { wiki: "Riko Amanai" },
  { wiki: "Misato Kuroi" },
  { wiki: "Yu Haibara", hair: ["Black"] },
  { wiki: "Yuki Tsukumo" },
  { wiki: "Naoya Zenin", name: "Naoya Zen'in", race: ["Human"] },
  { wiki: "Naobito Zenin", name: "Naobito Zen'in" },
  { wiki: "Haruta Shigemo" },
  { wiki: "Takuma Ino" },
  { wiki: "Arata Nitta" },
  { wiki: "Uraume", gender: "Unknown" },
  { wiki: "Miguel" },
  { wiki: "Larue" },
  { wiki: "Tengen" },
  { wiki: "Tsumiki Fushiguro" },
  { wiki: "Hajime Kashimo" },
  { wiki: "Hiromi Higuruma" },
  { wiki: "Kinji Hakari" },
  { wiki: "Fumihiko Takaba" },
  { wiki: "Ryu Ishigori" },
  { wiki: "Takako Uro" },
  { wiki: "Reggie Star" },
  { wiki: "Charles Bernard" },
  { wiki: "Hana Kurusu" },
  { wiki: "Kenjaku", arc: 5 },
  { wiki: "Ogi Zenin", name: "Ogi Zen'in" },
  { wiki: "Ogami", name: "Granny Ogami" },
];
